// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kihamo/boggart/providers/tvt/models"
)

// NewGetStorageInfoParams creates a new GetStorageInfoParams object
// with the default values initialized.
func NewGetStorageInfoParams() *GetStorageInfoParams {
	var ()
	return &GetStorageInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStorageInfoParamsWithTimeout creates a new GetStorageInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStorageInfoParamsWithTimeout(timeout time.Duration) *GetStorageInfoParams {
	var ()
	return &GetStorageInfoParams{

		timeout: timeout,
	}
}

// NewGetStorageInfoParamsWithContext creates a new GetStorageInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStorageInfoParamsWithContext(ctx context.Context) *GetStorageInfoParams {
	var ()
	return &GetStorageInfoParams{

		Context: ctx,
	}
}

// NewGetStorageInfoParamsWithHTTPClient creates a new GetStorageInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStorageInfoParamsWithHTTPClient(client *http.Client) *GetStorageInfoParams {
	var ()
	return &GetStorageInfoParams{
		HTTPClient: client,
	}
}

/*
GetStorageInfoParams contains all the parameters to send to the API endpoint
for the get storage info operation typically these are written to a http.Request
*/
type GetStorageInfoParams struct {

	/*Request*/
	Request models.Request

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get storage info params
func (o *GetStorageInfoParams) WithTimeout(timeout time.Duration) *GetStorageInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get storage info params
func (o *GetStorageInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get storage info params
func (o *GetStorageInfoParams) WithContext(ctx context.Context) *GetStorageInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get storage info params
func (o *GetStorageInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get storage info params
func (o *GetStorageInfoParams) WithHTTPClient(client *http.Client) *GetStorageInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get storage info params
func (o *GetStorageInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the get storage info params
func (o *GetStorageInfoParams) WithRequest(request models.Request) *GetStorageInfoParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the get storage info params
func (o *GetStorageInfoParams) SetRequest(request models.Request) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *GetStorageInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
