// Code generated by go-swagger; DO NOT EDIT.

package ussd

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kihamo/boggart/components/boggart/providers/hilink/models"
)

// SendUSSDReader is a Reader for the SendUSSD structure.
type SendUSSDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendUSSDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSendUSSDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendUSSDOK creates a SendUSSDOK with default headers values
func NewSendUSSDOK() *SendUSSDOK {
	return &SendUSSDOK{}
}

/*SendUSSDOK handles this case with default header values.

Successful operation
*/
type SendUSSDOK struct {
	Payload *models.USSD
}

func (o *SendUSSDOK) Error() string {
	return fmt.Sprintf("[POST /ussd/send][%d] sendUSSDOK  %+v", 200, o.Payload)
}

func (o *SendUSSDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.USSD)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
