// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	static "github.com/kihamo/boggart/providers/hikvision/static/models"
)

// GetNotificationHTTPHostReader is a Reader for the GetNotificationHTTPHost structure.
type GetNotificationHTTPHostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNotificationHTTPHostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNotificationHTTPHostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetNotificationHTTPHostOK creates a GetNotificationHTTPHostOK with default headers values
func NewGetNotificationHTTPHostOK() *GetNotificationHTTPHostOK {
	return &GetNotificationHTTPHostOK{}
}

/* GetNotificationHTTPHostOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetNotificationHTTPHostOK struct {
	Payload *static.HTTPHostNotification
}

func (o *GetNotificationHTTPHostOK) Error() string {
	return fmt.Sprintf("[GET /Event/notification/httpHosts/{httpHost}][%d] getNotificationHttpHostOK  %+v", 200, o.Payload)
}
func (o *GetNotificationHTTPHostOK) GetPayload() *static.HTTPHostNotification {
	return o.Payload
}

func (o *GetNotificationHTTPHostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(static.HTTPHostNotification)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
