// Code generated by go-swagger; DO NOT EDIT.

package image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kihamo/boggart/providers/hikvision/models"
)

// GetImageChannelsReader is a Reader for the GetImageChannels structure.
type GetImageChannelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageChannelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImageChannelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Image/channels] getImageChannels", response, response.Code())
	}
}

// NewGetImageChannelsOK creates a GetImageChannelsOK with default headers values
func NewGetImageChannelsOK() *GetImageChannelsOK {
	return &GetImageChannelsOK{}
}

/*
GetImageChannelsOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetImageChannelsOK struct {
	Payload models.ImageChannels
}

// IsSuccess returns true when this get image channels o k response has a 2xx status code
func (o *GetImageChannelsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get image channels o k response has a 3xx status code
func (o *GetImageChannelsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get image channels o k response has a 4xx status code
func (o *GetImageChannelsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get image channels o k response has a 5xx status code
func (o *GetImageChannelsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get image channels o k response a status code equal to that given
func (o *GetImageChannelsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get image channels o k response
func (o *GetImageChannelsOK) Code() int {
	return 200
}

func (o *GetImageChannelsOK) Error() string {
	return fmt.Sprintf("[GET /Image/channels][%d] getImageChannelsOK  %+v", 200, o.Payload)
}

func (o *GetImageChannelsOK) String() string {
	return fmt.Sprintf("[GET /Image/channels][%d] getImageChannelsOK  %+v", 200, o.Payload)
}

func (o *GetImageChannelsOK) GetPayload() models.ImageChannels {
	return o.Payload
}

func (o *GetImageChannelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
