// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VersionResponse version response
//
// swagger:model VersionResponse
type VersionResponse struct {

	// arch
	Arch string `json:"arch,omitempty"`

	// release
	Release string `json:"release,omitempty"`

	// sandbox
	Sandbox string `json:"sandbox,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this version response
func (m *VersionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this version response based on context it is used
func (m *VersionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VersionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionResponse) UnmarshalBinary(b []byte) error {
	var res VersionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
