// Code generated by go-swagger; DO NOT EDIT.

package state

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kihamo/boggart/providers/myheat/device/models"
)

// GetStateReader is a Reader for the GetState structure.
type GetStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /getState] getState", response, response.Code())
	}
}

// NewGetStateOK creates a GetStateOK with default headers values
func NewGetStateOK() *GetStateOK {
	return &GetStateOK{}
}

/*
GetStateOK describes a response with status code 200, with default header values.

Successful login
*/
type GetStateOK struct {
	Payload *models.State
}

// IsSuccess returns true when this get state o k response has a 2xx status code
func (o *GetStateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get state o k response has a 3xx status code
func (o *GetStateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get state o k response has a 4xx status code
func (o *GetStateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get state o k response has a 5xx status code
func (o *GetStateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get state o k response a status code equal to that given
func (o *GetStateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get state o k response
func (o *GetStateOK) Code() int {
	return 200
}

func (o *GetStateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /getState][%d] getStateOK %s", 200, payload)
}

func (o *GetStateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /getState][%d] getStateOK %s", 200, payload)
}

func (o *GetStateOK) GetPayload() *models.State {
	return o.Payload
}

func (o *GetStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.State)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
