// Code generated by go-swagger; DO NOT EDIT.

package state

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetObjStateParams creates a new SetObjStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetObjStateParams() *SetObjStateParams {
	return &SetObjStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetObjStateParamsWithTimeout creates a new SetObjStateParams object
// with the ability to set a timeout on a request.
func NewSetObjStateParamsWithTimeout(timeout time.Duration) *SetObjStateParams {
	return &SetObjStateParams{
		timeout: timeout,
	}
}

// NewSetObjStateParamsWithContext creates a new SetObjStateParams object
// with the ability to set a context for a request.
func NewSetObjStateParamsWithContext(ctx context.Context) *SetObjStateParams {
	return &SetObjStateParams{
		Context: ctx,
	}
}

// NewSetObjStateParamsWithHTTPClient creates a new SetObjStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetObjStateParamsWithHTTPClient(client *http.Client) *SetObjStateParams {
	return &SetObjStateParams{
		HTTPClient: client,
	}
}

/*
SetObjStateParams contains all the parameters to send to the API endpoint

	for the set obj state operation.

	Typically these are written to a http.Request.
*/
type SetObjStateParams struct {

	// Request.
	Request SetObjStateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set obj state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetObjStateParams) WithDefaults() *SetObjStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set obj state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetObjStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set obj state params
func (o *SetObjStateParams) WithTimeout(timeout time.Duration) *SetObjStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set obj state params
func (o *SetObjStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set obj state params
func (o *SetObjStateParams) WithContext(ctx context.Context) *SetObjStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set obj state params
func (o *SetObjStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set obj state params
func (o *SetObjStateParams) WithHTTPClient(client *http.Client) *SetObjStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set obj state params
func (o *SetObjStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the set obj state params
func (o *SetObjStateParams) WithRequest(request SetObjStateBody) *SetObjStateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the set obj state params
func (o *SetObjStateParams) SetRequest(request SetObjStateBody) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *SetObjStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
