// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MonitoringTrafficStatistics monitoring traffic statistics
//
// swagger:model MonitoringTrafficStatistics
type MonitoringTrafficStatistics struct {

	// current connect time
	CurrentConnectTime int64 `json:"CurrentConnectTime,omitempty" xml:"CurrentConnectTime,omitempty"`

	// current download
	CurrentDownload int64 `json:"CurrentDownload,omitempty" xml:"CurrentDownload,omitempty"`

	// current download rate
	CurrentDownloadRate int64 `json:"CurrentDownloadRate,omitempty" xml:"CurrentDownloadRate,omitempty"`

	// current upload
	CurrentUpload int64 `json:"CurrentUpload,omitempty" xml:"CurrentUpload,omitempty"`

	// current upload rate
	CurrentUploadRate int64 `json:"CurrentUploadRate,omitempty" xml:"CurrentUploadRate,omitempty"`

	// show traffic
	ShowTraffic int64 `json:"ShowTraffic,omitempty" xml:"showtraffic,omitempty"`

	// total connect time
	TotalConnectTime int64 `json:"TotalConnectTime,omitempty" xml:"TotalConnectTime,omitempty"`

	// total download
	TotalDownload int64 `json:"TotalDownload,omitempty" xml:"TotalDownload,omitempty"`

	// total upload
	TotalUpload int64 `json:"TotalUpload,omitempty" xml:"TotalUpload,omitempty"`
}

// Validate validates this monitoring traffic statistics
func (m *MonitoringTrafficStatistics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this monitoring traffic statistics based on context it is used
func (m *MonitoringTrafficStatistics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MonitoringTrafficStatistics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MonitoringTrafficStatistics) UnmarshalBinary(b []byte) error {
	var res MonitoringTrafficStatistics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
