// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SMSCount s m s count
//
// swagger:model SMSCount
type SMSCount struct {

	// local deleted
	LocalDeleted int64 `json:"LocalDeleted,omitempty" xml:"LocalDeleted,omitempty"`

	// local draft
	LocalDraft int64 `json:"LocalDraft,omitempty" xml:"LocalDraft,omitempty"`

	// local inbox
	LocalInbox int64 `json:"LocalInbox,omitempty" xml:"LocalInbox,omitempty"`

	// local max
	LocalMax int64 `json:"LocalMax,omitempty" xml:"LocalMax,omitempty"`

	// local outbox
	LocalOutbox int64 `json:"LocalOutbox,omitempty" xml:"LocalOutbox,omitempty"`

	// local unread
	LocalUnread int64 `json:"LocalUnread,omitempty" xml:"LocalUnread,omitempty"`

	// new msg
	NewMsg int64 `json:"NewMsg,omitempty" xml:"NewMsg,omitempty"`

	// sim draft
	SimDraft int64 `json:"SimDraft,omitempty" xml:"SimDraft,omitempty"`

	// sim inbox
	SimInbox int64 `json:"SimInbox,omitempty" xml:"SimInbox,omitempty"`

	// sim max
	SimMax int64 `json:"SimMax,omitempty" xml:"SimMax,omitempty"`

	// sim outbox
	SimOutbox int64 `json:"SimOutbox,omitempty" xml:"SimOutbox,omitempty"`

	// sim unread
	SimUnread int64 `json:"SimUnread,omitempty" xml:"SimUnread,omitempty"`

	// sim used
	SimUsed int64 `json:"SimUsed,omitempty" xml:"SimUsed,omitempty"`
}

// Validate validates this s m s count
func (m *SMSCount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this s m s count based on context it is used
func (m *SMSCount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SMSCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SMSCount) UnmarshalBinary(b []byte) error {
	var res SMSCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
