// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRootParams creates a new GetRootParams object
// with the default values initialized.
func NewGetRootParams() *GetRootParams {

	return &GetRootParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRootParamsWithTimeout creates a new GetRootParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRootParamsWithTimeout(timeout time.Duration) *GetRootParams {

	return &GetRootParams{

		timeout: timeout,
	}
}

// NewGetRootParamsWithContext creates a new GetRootParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRootParamsWithContext(ctx context.Context) *GetRootParams {

	return &GetRootParams{

		Context: ctx,
	}
}

// NewGetRootParamsWithHTTPClient creates a new GetRootParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRootParamsWithHTTPClient(client *http.Client) *GetRootParams {

	return &GetRootParams{
		HTTPClient: client,
	}
}

/*GetRootParams contains all the parameters to send to the API endpoint
for the get root operation typically these are written to a http.Request
*/
type GetRootParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get root params
func (o *GetRootParams) WithTimeout(timeout time.Duration) *GetRootParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get root params
func (o *GetRootParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get root params
func (o *GetRootParams) WithContext(ctx context.Context) *GetRootParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get root params
func (o *GetRootParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get root params
func (o *GetRootParams) WithHTTPClient(client *http.Client) *GetRootParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get root params
func (o *GetRootParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRootParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
