// Code generated by go-swagger; DO NOT EDIT.

package audio

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSourcesParams creates a new GetSourcesParams object
// with the default values initialized.
func NewGetSourcesParams() *GetSourcesParams {
	var ()
	return &GetSourcesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSourcesParamsWithTimeout creates a new GetSourcesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSourcesParamsWithTimeout(timeout time.Duration) *GetSourcesParams {
	var ()
	return &GetSourcesParams{

		timeout: timeout,
	}
}

// NewGetSourcesParamsWithContext creates a new GetSourcesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSourcesParamsWithContext(ctx context.Context) *GetSourcesParams {
	var ()
	return &GetSourcesParams{

		Context: ctx,
	}
}

// NewGetSourcesParamsWithHTTPClient creates a new GetSourcesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSourcesParamsWithHTTPClient(client *http.Client) *GetSourcesParams {
	var ()
	return &GetSourcesParams{
		HTTPClient: client,
	}
}

/*
GetSourcesParams contains all the parameters to send to the API endpoint
for the get sources operation typically these are written to a http.Request
*/
type GetSourcesParams struct {

	/*AcceptLanguage
	  language

	*/
	AcceptLanguage *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sources params
func (o *GetSourcesParams) WithTimeout(timeout time.Duration) *GetSourcesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sources params
func (o *GetSourcesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sources params
func (o *GetSourcesParams) WithContext(ctx context.Context) *GetSourcesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sources params
func (o *GetSourcesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sources params
func (o *GetSourcesParams) WithHTTPClient(client *http.Client) *GetSourcesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sources params
func (o *GetSourcesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAcceptLanguage adds the acceptLanguage to the get sources params
func (o *GetSourcesParams) WithAcceptLanguage(acceptLanguage *string) *GetSourcesParams {
	o.SetAcceptLanguage(acceptLanguage)
	return o
}

// SetAcceptLanguage adds the acceptLanguage to the get sources params
func (o *GetSourcesParams) SetAcceptLanguage(acceptLanguage *string) {
	o.AcceptLanguage = acceptLanguage
}

// WriteToRequest writes these params to a swagger request
func (o *GetSourcesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AcceptLanguage != nil {

		// header param Accept-Language
		if err := r.SetHeaderParam("Accept-Language", *o.AcceptLanguage); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
