// Code generated by go-swagger; DO NOT EDIT.

package monitoring

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kihamo/boggart/components/boggart/providers/hilink/models"
)

// GetMonitoringStatusReader is a Reader for the GetMonitoringStatus structure.
type GetMonitoringStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMonitoringStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMonitoringStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMonitoringStatusOK creates a GetMonitoringStatusOK with default headers values
func NewGetMonitoringStatusOK() *GetMonitoringStatusOK {
	return &GetMonitoringStatusOK{}
}

/*GetMonitoringStatusOK handles this case with default header values.

Successful operation
*/
type GetMonitoringStatusOK struct {
	Payload *models.MonitoringStatus
}

func (o *GetMonitoringStatusOK) Error() string {
	return fmt.Sprintf("[GET /monitoring/status][%d] getMonitoringStatusOK  %+v", 200, o.Payload)
}

func (o *GetMonitoringStatusOK) GetPayload() *models.MonitoringStatus {
	return o.Payload
}

func (o *GetMonitoringStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MonitoringStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
