// Code generated by go-swagger; DO NOT EDIT.

package ptz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGotoPtzPresetParams creates a new GotoPtzPresetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGotoPtzPresetParams() *GotoPtzPresetParams {
	return &GotoPtzPresetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGotoPtzPresetParamsWithTimeout creates a new GotoPtzPresetParams object
// with the ability to set a timeout on a request.
func NewGotoPtzPresetParamsWithTimeout(timeout time.Duration) *GotoPtzPresetParams {
	return &GotoPtzPresetParams{
		timeout: timeout,
	}
}

// NewGotoPtzPresetParamsWithContext creates a new GotoPtzPresetParams object
// with the ability to set a context for a request.
func NewGotoPtzPresetParamsWithContext(ctx context.Context) *GotoPtzPresetParams {
	return &GotoPtzPresetParams{
		Context: ctx,
	}
}

// NewGotoPtzPresetParamsWithHTTPClient creates a new GotoPtzPresetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGotoPtzPresetParamsWithHTTPClient(client *http.Client) *GotoPtzPresetParams {
	return &GotoPtzPresetParams{
		HTTPClient: client,
	}
}

/* GotoPtzPresetParams contains all the parameters to send to the API endpoint
   for the goto ptz preset operation.

   Typically these are written to a http.Request.
*/
type GotoPtzPresetParams struct {

	/* Channel.

	   Channel ID

	   Format: uint64
	*/
	Channel uint64

	/* Preset.

	   Preset ID

	   Format: uint64
	*/
	Preset uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the goto ptz preset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GotoPtzPresetParams) WithDefaults() *GotoPtzPresetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the goto ptz preset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GotoPtzPresetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the goto ptz preset params
func (o *GotoPtzPresetParams) WithTimeout(timeout time.Duration) *GotoPtzPresetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the goto ptz preset params
func (o *GotoPtzPresetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the goto ptz preset params
func (o *GotoPtzPresetParams) WithContext(ctx context.Context) *GotoPtzPresetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the goto ptz preset params
func (o *GotoPtzPresetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the goto ptz preset params
func (o *GotoPtzPresetParams) WithHTTPClient(client *http.Client) *GotoPtzPresetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the goto ptz preset params
func (o *GotoPtzPresetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannel adds the channel to the goto ptz preset params
func (o *GotoPtzPresetParams) WithChannel(channel uint64) *GotoPtzPresetParams {
	o.SetChannel(channel)
	return o
}

// SetChannel adds the channel to the goto ptz preset params
func (o *GotoPtzPresetParams) SetChannel(channel uint64) {
	o.Channel = channel
}

// WithPreset adds the preset to the goto ptz preset params
func (o *GotoPtzPresetParams) WithPreset(preset uint64) *GotoPtzPresetParams {
	o.SetPreset(preset)
	return o
}

// SetPreset adds the preset to the goto ptz preset params
func (o *GotoPtzPresetParams) SetPreset(preset uint64) {
	o.Preset = preset
}

// WriteToRequest writes these params to a swagger request
func (o *GotoPtzPresetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel
	if err := r.SetPathParam("channel", swag.FormatUint64(o.Channel)); err != nil {
		return err
	}

	// path param preset
	if err := r.SetPathParam("preset", swag.FormatUint64(o.Preset)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
