switch:
  - platform: gpio
    id: relay_${id}
    name: Relay ${name} fire
    pin:
      pcf8574: outputs
      number: ${relay}
      mode: OUTPUT
      inverted: ${relay_inverted}
    icon: mdi:toggle-switch-variant
    web_server:
      sorting_group_id: floor_${id}
      sorting_weight: 1

sensor:
  - platform: mqtt_subscribe
    id: temperature_current_${id}
    name: Temperature current ${name}
    topic: ${topic_current}
    icon: mdi:thermometer-lines
    filters:
      # округляем и усредняем присылаемые значение, чтобы сгладить колебания температуры
      # иначе при приближению к таргету он начнет передергивать привод постояно
      - sliding_window_moving_average:
          window_size: 10 # фактически раз в 10 минут, так как показания снимаются каждую минуту
          send_every: 3
      - round: 1
    web_server:
      sorting_group_id: floor_${id}
      sorting_weight: 3
    on_value:
      then:
        - script.execute: toggle_relay_by_target_temperature_${id}

number:
  - platform: template
    name: Target temperature ${name}
    id: temperature_target_${id}
    min_value: ${temperature_target_value_min}
    max_value: ${temperature_target_value_max}
    step: ${temperature_target_step}
    initial_value: ${temperature_target_value_initial}
    restore_value: true
    mode: slider
    optimistic: true
    icon: mdi:thermometer-check
    web_server:
      sorting_group_id: floor_${id}
      sorting_weight: 4
    on_value:
      then:
        - script.execute: toggle_relay_by_target_temperature_${id}

# https://community.home-assistant.io/t/reduce-the-size-of-config-file-yaml-many-repeats/499872/2

script:
  - id: toggle_relay_by_target_temperature_${id}
    then:
      - lambda: |-
          float currentT = id(temperature_current_${id}).state;
          float targetT = id(temperature_target_${id}).state;
          auto relay = id(relay_${id}).state;

          // ESP_LOGD("thermostat", "Fire event for ${id}. Current: %f target: %f relay: %s compare: %s", currentT, targetT, relay ? "ON" : "OFF", targetT > currentT ? "ON" : "OFF");

          // включаем нагрев, если до таргета не хватает больше чем 1 градус
          if (targetT > currentT) {
            if (!relay) {
              id(relay_${id}).turn_on();

              ESP_LOGI("thermostat", "Servo OPEN for ${id}. Current: %f target: %f relay: %s", currentT, targetT, relay ? "ON" : "OFF");
            }
          // если остается меньше одного градус или таргет ниже, то начинаем выключать
          } else if (relay) {
            id(relay_${id}).turn_off();

            ESP_LOGI("thermostat", "Servo turn CLOSE for ${id}. Current: %f target: %f relay: %s", currentT, targetT, relay ? "ON" : "OFF");
          }
