# https://www.smarty.ninja/en/ecosystems/sonoff/nspanel-and-esphome/
# http://psenyukov.ru/%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B0-sonoff-nspanel-%D0%B2-esphome-%D0%B8-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82/
# https://github.com/marcfager/nspanel-mf/blob/main/esphome/nspanel-mf.yaml
# https://github.com/esphome/issues/issues/2423

#  Device Model:     NX4832F035_011C
#  Firmware Version: 51
#  Serial Number:    8E89340158B66677
#  Flash Size:       16777216
#  Wake On Touch:    True
#  Wake Up Page :       4

debug:

substitutions:
  node_name: !secret device_014_node_name
  ip_address: !secret device_014_ip_address

packages:
  common: !include ./_includes/common.yaml
  wifi: !include ./_includes/wifi/home.yaml
  binary_sensor: !include ./_includes/binary_sensor.yaml
  sensor: !include ./_includes/sensor.yaml
  switch: !include ./_includes/switch.yaml
  text_sensor: !include ./_includes/text_sensor.yaml
  time: !include ./_includes/time.yaml

esphome:
  comment: !secret device_014_comment

esp32:
  board: esp32dev

logger:
  level: "DEBUG"
  baud_rate: 0

#api:
#  services:
#    - service: upload_tft
#      then:
#        - lambda: 'id(display_nextion)->upload_tft();'

uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200
  id: tf_uart

#external_components:
#  - source: github://pr#2956
#    components: [nextion]
#    refresh: 1h

# speaker
output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21
rtttl:
  id: buzzer
  output: buzzer_out

button:
  - platform: template
    name: TFT Upload
    device_class: update
    on_press:
      - lambda: 'id(display_nextion).upload_tft();'

# Binary sensors
binary_sensor:
  # Left button below the display
  - platform: gpio
    id: button_left
    name: Left Button
    pin:
      number: 14
      inverted: true
    on_click:
      - switch.toggle: relay_left

  # Right button below the display
  - platform: gpio
    id: button_right
    name: Right Button
    pin:
      number: 27
      inverted: true
    on_click:
      - switch.toggle: relay_right

switch:
  # Physical relay 1
  - platform: gpio
    id: relay_left
    name: Relay left
    pin:
      number: 22

  # Physical relay 2
  - platform: gpio
    id: relay_right
    name: Relay right
    pin:
      number: 19

  # Turn screen power on/off. Easy way to configure the screen power control, but this should not be used from HA, as all components must be re-initialized afterwards. For lights, names of lights etc. this practically means that the state must change once to happen.
  - platform: gpio
    name: Screen Power
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON

sensor:
  # Internal temperature sensor, adc value
  - platform: adc
    id: ntc_source
    name: NTC sensor
    pin: 38
    update_interval: 10s
    attenuation: 11db

  # Internal temperature sensor, adc reading converted to resistance (calculation)
  - platform: resistance
    id: resistance_sensor
    name: NTC resistance sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  # Internal temperature sensor, resistance to temperature (calculation)
  - platform: ntc
    id: temperature
    name: Temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm

display:
  - platform: nextion
    id: display_nextion
    uart_id: tf_uart
    tft_url: !secret device_014_nextion_update_url
#    update_interval: 60s
#    auto_wake_on_touch: true
#    wake_up_page: 4
#    on_setup:
#      then:
#         Enable 1 light page (up to 4 available)
#        - lambda: id(display_nextion).send_command_printf("Lights.pages.val=1");
#        - lambda: id(display_nextion).send_command_printf("page 4");
#        - switch.template.publish:
#            id: nextion_init
#            state: on