# https://www.smarty.ninja/en/ecosystems/sonoff/nspanel-and-esphome/
# http://psenyukov.ru/%D0%BF%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B0-sonoff-nspanel-%D0%B2-esphome-%D0%B8-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82/
# https://github.com/marcfager/nspanel-mf/blob/main/esphome/nspanel-mf.yaml
# https://github.com/esphome/issues/issues/2423
# https://github.com/esphome/issues/issues/5161

#  Device Model:     NX4832F035_011C
#  Firmware Version: 51
#  Serial Number:    8E89340158B66677
#  Flash Size:       16777216
#  Wake On Touch:    True
#  Wake Up Page :       4

# update 2023-12-03
#
# 0. Отключить питание
# 1. Подключить пины на плане
#    GND-GND
#    RX - TX
#    TX - RX
#    3.3 - 3.3
#    IO0 - замкнуть на GND на самой плате (короткие коннекторы 8 штук)
#    5 - 5 (подпаянный) ???
# 2. Прошить свежий ESPHome командой esphome run device_014.yaml
# 3. Если постоянно перезагружается после прошивки, значит питания не достаточно 3.3в
#    для запуска wifi, нужно подключить 5в
# 4.

debug:

substitutions:
  node_name: !secret device_014_node_name
  ip_address: !secret device_014_ip_address

  device_name: !secret device_014_node_name
  nextion_update_url: !secret device_014_nextion_update_url
  wifi_ssid: !secret home_wifi_ssid
  wifi_password: !secret home_wifi_password

wifi:
  use_address: ${ip_address}
  fast_connect: true # чтобы подключаться к скрытой сети, отключает предварительное сканирование

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s
  common: !include ./_includes/common.yaml
  binary_sensor: !include ./_includes/binary_sensor.yaml
  sensor: !include ./_includes/sensor.yaml
  switch: !include ./_includes/switch.yaml
  text_sensor: !include ./_includes/text_sensor.yaml
  time: !include ./_includes/time.yaml

esphome:
  comment: !secret device_014_comment
  platformio_options:
    # крайне важный параметр, так как где1-то в обновлениях все по умолчанию стало 460800
    # а устройство это не поддерживает
    upload_speed: 115200

esp32:
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 115200
