# SNW-2SR waterproof lug
#
# P7  -- physical button
# P8  -- blue led & relay ?
# P9  -- red led
#
# BL0937 power meter
# https://www.belling.com.cn/media/file_object/bel_product/BL0937/datasheet/BL0937_V1.02_en.pdf
# P26 -- SEL
# P24 -- CF1
# P6  -- CF

substitutions:
  node_name: !secret device_019_node_name
  ip_address: !secret device_019_ip_address

packages:
  common: !include ./_includes/common.yaml
  wifi: !include ./_includes/wifi/home.yaml
  binary_sensor: !include ./_includes/binary_sensor.yaml
  sensor: !include ./_includes/sensor.yaml
  switch: !include ./_includes/switch.yaml
  text_sensor: !include ./_includes/text_sensor.yaml
  time: !include ./_includes/time.yaml

bk72xx:
  board: cb3s

switch:
  - platform: gpio
    pin: P8
    id: "relay"
    name: "Power relay"
    on_turn_off:
      - light.turn_on: "led_red"
    on_turn_on:
      - light.turn_off: "led_red"
    restore_mode: RESTORE_DEFAULT_ON

sensor:
  # https://github.com/Liionboy/esphome_beken_yaml/blob/874bf31d59f741cd6ef2e6c88810322cd54e2910/esphome_beken_device/smart-socket-dededeman.yaml
  # https://github.com/muhlba91/homelab-esphome-firmware/blob/ed7d66f78978af8c80037a994d70c793c07db146/config/shelly/plug/shelly-plug-tech-hub.conf.yml#L143
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: P26
      inverted: true
    cf_pin:
      number: P24
      inverted: true
    cf1_pin:
      number: P6
      inverted: true
    current:
      id: "amperage"
      name: "Amperage"
      unit_of_measurement: A
      accuracy_decimals: 3
#      filters:
#        - multiply: 0.3100151976971161
    voltage:
      id: "voltage"
      name: "Voltage"
      unit_of_measurement: V
    power:
      id: "power"
      name: "Power in watts"
      unit_of_measurement: W
      accuracy_decimals: 4
#      filters:
#        - calibrate_linear:
#            - 0.0 -> 0.0
#            - ${power_cal_meas} -> ${power_cal_real}
    change_mode_every: 2
#    voltage_divider: 778
#    current_resistor: 0.001008755324183625
    update_interval: 5s
  - platform: total_daily_energy
    name: "Total Daily Energy"
    icon: "mdi:current-ac"
    power_id: "power"

binary_sensor:
  - platform: gpio
    pin:
      number: P7
      inverted: true
      mode: INPUT_PULLUP
    id: "button"
    name: "Hardware button"
    internal: true
    on_press:
      - switch.toggle: relay

light:
  - platform: status_led
    pin: P9
    id: "led_red"
    name: "LED red"

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version