substitutions:
  node_name: !secret device_010_node_name
  ip_address: !secret device_010_ip_address

packages:
  common: !include ./_includes/common.yaml
  wifi: !include ./_includes/wifi/villa.yaml
  #wifi: !include ./_includes/wifi/home.yaml
  binary_sensor: !include ./_includes/binary_sensor.yaml
  sensor: !include ./_includes/sensor.yaml
  switch: !include ./_includes/switch.yaml
  text_sensor: !include ./_includes/text_sensor.yaml
  time: !include ./_includes/time.yaml

esphome:
  comment: !secret device_010_comment
#  platformio_options:
#    upload_speed: 460800
#    board_build.f_cpu: 80000000L

esp32:
  board: nodemcu-32s

api:
  reboot_timeout: 0s

debug:

logger:
  level: DEBUG
  baud_rate: 115200

mqtt:
  log_topic: null

external_components:
  - source:
      type: local
      path: ./external_components
#  - source: github://oxan/esphome-stream-server

#stream_server:
#  uart_id: uart_bus
#  port: 1234

uart:
  id: uart_bus
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO17
  rx_pin: GPIO16
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      bytes: 60
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ':');

i2c:
  sda: SDA
  scl: SCL
  scan: false
  id: i2c_bus

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: total_daily_energy
    name: "Total Daily Energy"
    icon: "mdi:current-ac"
    power_id: "power"
    method: "trapezoid"
  - platform: mercury_v3
#    address: !secret device_010_mercury_address
    update_interval: 60s
    phase_a:
      voltage:
        id: "phase1_voltage"
        name: "Phase 1 voltage"
      current:
        id: "phase1_current"
        name: "Phase 1 current"
      power:
        id: "phase1_power"
        name: "Phase 1 power"
    phase_b:
      voltage:
        id: "phase2_voltage"
        name: "Phase 2 voltage"
      current:
        id: "phase2_current"
        name: "Phase 2 current"
      power:
        id: "phase2_power"
        name: "Phase 2 power"
    phase_c:
      voltage:
        id: "phase3_voltage"
        name: "Phase 3 voltage"
      current:
        id: "phase3_current"
        name: "Phase 3 current"
      power:
        id: "phase3_power"
        name: "Phase 3 power"
    tariff_1:
      id: "tariff_1"
      name: "Tariff 1"
      icon: "mdi:flash"
    power:
      id: "power"
      name: "Power"

  - platform: bmp280_i2c
    update_interval: 10s
    temperature:
      id: temperature
      name: "Temperature"
      oversampling: 16x
#      filters:
#        - offset: -5.9
    pressure:
      id: pressure
      name: "Pressure"
      unit_of_measurement: "mmHg"
      filters:
        - multiply: 0.75006375541921
    address: 0x76

binary_sensor:
  - platform: gpio
    id: "door"
    name: "Entrance door"
    icon: "mdi:door"
    pin:
      number: GPIO32
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false
  - platform: gpio
    id: "window"
    name: "Window"
    icon: "mdi:window"
    pin:
      number: GPIO33
      mode:
        input: true
        pullup: true
        output: false
        open_drain: false
        pulldown: false

  - platform: gpio
    pin: GPIO26
    name: "PIR Motion detector"
    device_class: "motion"
