package boggart // import "github.com/kihamo/boggart"

//go:generate /bin/bash -c "find components/boggart/internal/locales/ -name \\*.po -execdir /bin/bash -c 'msgfmt {} -o `basename {} .po`.mo' '{}' \\;"
//go:generate /bin/bash -c "find components/boggart/bind/alsa/locales/ -name \\*.po -execdir /bin/bash -c 'msgfmt {} -o `basename {} .po`.mo' '{}' \\;"
//go:generate /bin/bash -c "find components/boggart/bind/astro/sun/locales/ -name \\*.po -execdir /bin/bash -c 'msgfmt {} -o `basename {} .po`.mo' '{}' \\;"
//go:generate /bin/bash -c "find components/boggart/bind/chromecast/locales/ -name \\*.po -execdir /bin/bash -c 'msgfmt {} -o `basename {} .po`.mo' '{}' \\;"
//go:generate /bin/bash -c "find components/boggart/bind/homie/esp/locales/ -name \\*.po -execdir /bin/bash -c 'msgfmt {} -o `basename {} .po`.mo' '{}' \\;"
//go:generate /bin/bash -c "find components/boggart/bind/mercury/locales/ -name \\*.po -execdir /bin/bash -c 'msgfmt {} -o `basename {} .po`.mo' '{}' \\;"
//go:generate /bin/bash -c "find components/boggart/bind/lg_webos/locales/ -name \\*.po -execdir /bin/bash -c 'msgfmt {} -o `basename {} .po`.mo' '{}' \\;"
//go:generate /bin/bash -c "find components/mqtt/internal/locales/ -name \\*.po -execdir /bin/bash -c 'msgfmt {} -o `basename {} .po`.mo' '{}' \\;"
//go:generate /bin/bash -c "goimports -w `find . -type f -name '*.go' -not -path './vendor/*' -not -name 'bindata_assetfs.go'`"
//go:generate /bin/bash -c "cd components/boggart/internal && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=internal -nometadata -nomemcopy templates/... assets/... locales/..."
//go:generate /bin/bash -c "cd components/boggart/bind/alsa && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=alsa -nometadata -nomemcopy templates/... locales/..."
//go:generate /bin/bash -c "cd components/boggart/bind/astro/sun && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=sun -nometadata -nomemcopy templates/... locales/..."
//go:generate /bin/bash -c "cd components/boggart/bind/chromecast && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=chromecast -nometadata -nomemcopy templates/... locales/..."
//go:generate /bin/bash -c "cd components/boggart/bind/homie/esp && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=esp -nometadata -nomemcopy templates/... locales/..."
//go:generate /bin/bash -c "cd components/boggart/bind/lg_webos && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=lg_webos -nometadata -nomemcopy templates/... locales/..."
//go:generate /bin/bash -c "cd components/boggart/bind/mercury && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=mercury -nometadata -nomemcopy templates/... locales/..."
//go:generate /bin/bash -c "cd components/boggart && enumer -type=BindStatus -trimprefix=BindStatus -output=bind_status_enumer.go"
//go:generate /bin/bash -c "cd components/mqtt/internal && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=internal -nometadata -nomemcopy templates/... locales/..."
//go:generate /bin/bash -c "cd components/voice/internal && go-bindata-assetfs -ignore='(.*?[.]po$)' -o ./bindata_assetfs.go -pkg=internal -nometadata -nomemcopy templates/..."
//go:generate /bin/bash -c "cd components/boggart/bind/alsa && enumer -type=Status -trimprefix=Status -output=status_enumer.go -transform=snake"
//go:generate /bin/bash -c "easyjson components/boggart/internal/handlers/manager.go"
