// Code generated by go-swagger; DO NOT EDIT.

package web_server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWebServerSessionParams creates a new GetWebServerSessionParams object
// with the default values initialized.
func NewGetWebServerSessionParams() *GetWebServerSessionParams {

	return &GetWebServerSessionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWebServerSessionParamsWithTimeout creates a new GetWebServerSessionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWebServerSessionParamsWithTimeout(timeout time.Duration) *GetWebServerSessionParams {

	return &GetWebServerSessionParams{

		timeout: timeout,
	}
}

// NewGetWebServerSessionParamsWithContext creates a new GetWebServerSessionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWebServerSessionParamsWithContext(ctx context.Context) *GetWebServerSessionParams {

	return &GetWebServerSessionParams{

		Context: ctx,
	}
}

// NewGetWebServerSessionParamsWithHTTPClient creates a new GetWebServerSessionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWebServerSessionParamsWithHTTPClient(client *http.Client) *GetWebServerSessionParams {

	return &GetWebServerSessionParams{
		HTTPClient: client,
	}
}

/*GetWebServerSessionParams contains all the parameters to send to the API endpoint
for the get web server session operation typically these are written to a http.Request
*/
type GetWebServerSessionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get web server session params
func (o *GetWebServerSessionParams) WithTimeout(timeout time.Duration) *GetWebServerSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get web server session params
func (o *GetWebServerSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get web server session params
func (o *GetWebServerSessionParams) WithContext(ctx context.Context) *GetWebServerSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get web server session params
func (o *GetWebServerSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get web server session params
func (o *GetWebServerSessionParams) WithHTTPClient(client *http.Client) *GetWebServerSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get web server session params
func (o *GetWebServerSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetWebServerSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
