// Code generated by go-swagger; DO NOT EDIT.

package habmin_designer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostDesignRefReader is a Reader for the PostDesignRef structure.
type PostDesignRefReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDesignRefReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewPostDesignRefDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewPostDesignRefDefault creates a PostDesignRefDefault with default headers values
func NewPostDesignRefDefault(code int) *PostDesignRefDefault {
	return &PostDesignRefDefault{
		_statusCode: code,
	}
}

/*PostDesignRefDefault handles this case with default header values.

successful operation
*/
type PostDesignRefDefault struct {
	_statusCode int
}

// Code gets the status code for the post design ref default response
func (o *PostDesignRefDefault) Code() int {
	return o._statusCode
}

func (o *PostDesignRefDefault) Error() string {
	return fmt.Sprintf("[POST /habmin/designer][%d] postDesignRef default ", o._statusCode)
}

func (o *PostDesignRefDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
