// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// AddMemberReader is a Reader for the AddMember structure.
type AddMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddMemberOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewAddMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewAddMemberMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddMemberOK creates a AddMemberOK with default headers values
func NewAddMemberOK() *AddMemberOK {
	return &AddMemberOK{}
}

/*AddMemberOK handles this case with default header values.

OK
*/
type AddMemberOK struct {
}

func (o *AddMemberOK) Error() string {
	return fmt.Sprintf("[PUT /items/{itemName}/members/{memberItemName}][%d] addMemberOK ", 200)
}

func (o *AddMemberOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddMemberNotFound creates a AddMemberNotFound with default headers values
func NewAddMemberNotFound() *AddMemberNotFound {
	return &AddMemberNotFound{}
}

/*AddMemberNotFound handles this case with default header values.

Item or member item not found or item is not of type group item.
*/
type AddMemberNotFound struct {
}

func (o *AddMemberNotFound) Error() string {
	return fmt.Sprintf("[PUT /items/{itemName}/members/{memberItemName}][%d] addMemberNotFound ", 404)
}

func (o *AddMemberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddMemberMethodNotAllowed creates a AddMemberMethodNotAllowed with default headers values
func NewAddMemberMethodNotAllowed() *AddMemberMethodNotAllowed {
	return &AddMemberMethodNotAllowed{}
}

/*AddMemberMethodNotAllowed handles this case with default header values.

Member item is not editable.
*/
type AddMemberMethodNotAllowed struct {
}

func (o *AddMemberMethodNotAllowed) Error() string {
	return fmt.Sprintf("[PUT /items/{itemName}/members/{memberItemName}][%d] addMemberMethodNotAllowed ", 405)
}

func (o *AddMemberMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
