// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kihamo/boggart/providers/openhab/models"
)

// NewAddMetadataParams creates a new AddMetadataParams object
// with the default values initialized.
func NewAddMetadataParams() *AddMetadataParams {
	var ()
	return &AddMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddMetadataParamsWithTimeout creates a new AddMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddMetadataParamsWithTimeout(timeout time.Duration) *AddMetadataParams {
	var ()
	return &AddMetadataParams{

		timeout: timeout,
	}
}

// NewAddMetadataParamsWithContext creates a new AddMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddMetadataParamsWithContext(ctx context.Context) *AddMetadataParams {
	var ()
	return &AddMetadataParams{

		Context: ctx,
	}
}

// NewAddMetadataParamsWithHTTPClient creates a new AddMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddMetadataParamsWithHTTPClient(client *http.Client) *AddMetadataParams {
	var ()
	return &AddMetadataParams{
		HTTPClient: client,
	}
}

/*AddMetadataParams contains all the parameters to send to the API endpoint
for the add metadata operation typically these are written to a http.Request
*/
type AddMetadataParams struct {

	/*Body
	  metadata

	*/
	Body *models.MetadataDTO
	/*Itemname
	  item name

	*/
	Itemname string
	/*Namespace
	  namespace

	*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add metadata params
func (o *AddMetadataParams) WithTimeout(timeout time.Duration) *AddMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add metadata params
func (o *AddMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add metadata params
func (o *AddMetadataParams) WithContext(ctx context.Context) *AddMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add metadata params
func (o *AddMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add metadata params
func (o *AddMetadataParams) WithHTTPClient(client *http.Client) *AddMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add metadata params
func (o *AddMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add metadata params
func (o *AddMetadataParams) WithBody(body *models.MetadataDTO) *AddMetadataParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add metadata params
func (o *AddMetadataParams) SetBody(body *models.MetadataDTO) {
	o.Body = body
}

// WithItemname adds the itemname to the add metadata params
func (o *AddMetadataParams) WithItemname(itemname string) *AddMetadataParams {
	o.SetItemname(itemname)
	return o
}

// SetItemname adds the itemname to the add metadata params
func (o *AddMetadataParams) SetItemname(itemname string) {
	o.Itemname = itemname
}

// WithNamespace adds the namespace to the add metadata params
func (o *AddMetadataParams) WithNamespace(namespace string) *AddMetadataParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the add metadata params
func (o *AddMetadataParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *AddMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param itemname
	if err := r.SetPathParam("itemname", o.Itemname); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
