// Code generated by go-swagger; DO NOT EDIT.

package ptz

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kihamo/boggart/components/boggart/providers/hikvision2/models"
)

// SetPtzContinuousReader is a Reader for the SetPtzContinuous structure.
type SetPtzContinuousReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetPtzContinuousReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetPtzContinuousOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetPtzContinuousOK creates a SetPtzContinuousOK with default headers values
func NewSetPtzContinuousOK() *SetPtzContinuousOK {
	return &SetPtzContinuousOK{}
}

/*SetPtzContinuousOK handles this case with default header values.

Successful operation
*/
type SetPtzContinuousOK struct {
	Payload *models.Status
}

func (o *SetPtzContinuousOK) Error() string {
	return fmt.Sprintf("[PUT /PTZCtrl/channels/{channel}/continuous][%d] setPtzContinuousOK  %+v", 200, o.Payload)
}

func (o *SetPtzContinuousOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
