// Code generated by go-swagger; DO NOT EDIT.

package content_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kihamo/boggart/providers/hikvision/models"
)

// GetStorageReader is a Reader for the GetStorage structure.
type GetStorageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStorageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStorageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStorageOK creates a GetStorageOK with default headers values
func NewGetStorageOK() *GetStorageOK {
	return &GetStorageOK{}
}

/* GetStorageOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetStorageOK struct {
	Payload *models.Storage
}

func (o *GetStorageOK) Error() string {
	return fmt.Sprintf("[GET /ContentMgmt/Storage][%d] getStorageOK  %+v", 200, o.Payload)
}
func (o *GetStorageOK) GetPayload() *models.Storage {
	return o.Payload
}

func (o *GetStorageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Storage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
