// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStatusExParams creates a new GetStatusExParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStatusExParams() *GetStatusExParams {
	return &GetStatusExParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStatusExParamsWithTimeout creates a new GetStatusExParams object
// with the ability to set a timeout on a request.
func NewGetStatusExParamsWithTimeout(timeout time.Duration) *GetStatusExParams {
	return &GetStatusExParams{
		timeout: timeout,
	}
}

// NewGetStatusExParamsWithContext creates a new GetStatusExParams object
// with the ability to set a context for a request.
func NewGetStatusExParamsWithContext(ctx context.Context) *GetStatusExParams {
	return &GetStatusExParams{
		Context: ctx,
	}
}

// NewGetStatusExParamsWithHTTPClient creates a new GetStatusExParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStatusExParamsWithHTTPClient(client *http.Client) *GetStatusExParams {
	return &GetStatusExParams{
		HTTPClient: client,
	}
}

/*
GetStatusExParams contains all the parameters to send to the API endpoint

	for the get status ex operation.

	Typically these are written to a http.Request.
*/
type GetStatusExParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get status ex params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStatusExParams) WithDefaults() *GetStatusExParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get status ex params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStatusExParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get status ex params
func (o *GetStatusExParams) WithTimeout(timeout time.Duration) *GetStatusExParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get status ex params
func (o *GetStatusExParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get status ex params
func (o *GetStatusExParams) WithContext(ctx context.Context) *GetStatusExParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get status ex params
func (o *GetStatusExParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get status ex params
func (o *GetStatusExParams) WithHTTPClient(client *http.Client) *GetStatusExParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get status ex params
func (o *GetStatusExParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetStatusExParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
