// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HistoryDataBean history data bean
// swagger:model HistoryDataBean
type HistoryDataBean struct {

	// state
	State string `json:"state,omitempty"`

	// time
	Time int64 `json:"time,omitempty"`
}

// Validate validates this history data bean
func (m *HistoryDataBean) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HistoryDataBean) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HistoryDataBean) UnmarshalBinary(b []byte) error {
	var res HistoryDataBean
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
