// Code generated by go-swagger; DO NOT EDIT.

package habmin_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kihamo/boggart/components/openhab/models"
)

// NewHTTPPutModelSourceParams creates a new HTTPPutModelSourceParams object
// with the default values initialized.
func NewHTTPPutModelSourceParams() *HTTPPutModelSourceParams {
	var ()
	return &HTTPPutModelSourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHTTPPutModelSourceParamsWithTimeout creates a new HTTPPutModelSourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHTTPPutModelSourceParamsWithTimeout(timeout time.Duration) *HTTPPutModelSourceParams {
	var ()
	return &HTTPPutModelSourceParams{

		timeout: timeout,
	}
}

// NewHTTPPutModelSourceParamsWithContext creates a new HTTPPutModelSourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewHTTPPutModelSourceParamsWithContext(ctx context.Context) *HTTPPutModelSourceParams {
	var ()
	return &HTTPPutModelSourceParams{

		Context: ctx,
	}
}

// NewHTTPPutModelSourceParamsWithHTTPClient creates a new HTTPPutModelSourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHTTPPutModelSourceParamsWithHTTPClient(client *http.Client) *HTTPPutModelSourceParams {
	var ()
	return &HTTPPutModelSourceParams{
		HTTPClient: client,
	}
}

/*HTTPPutModelSourceParams contains all the parameters to send to the API endpoint
for the http put model source operation typically these are written to a http.Request
*/
type HTTPPutModelSourceParams struct {

	/*Body*/
	Body *models.RuleSourceBean
	/*Modelname*/
	Modelname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the http put model source params
func (o *HTTPPutModelSourceParams) WithTimeout(timeout time.Duration) *HTTPPutModelSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the http put model source params
func (o *HTTPPutModelSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the http put model source params
func (o *HTTPPutModelSourceParams) WithContext(ctx context.Context) *HTTPPutModelSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the http put model source params
func (o *HTTPPutModelSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the http put model source params
func (o *HTTPPutModelSourceParams) WithHTTPClient(client *http.Client) *HTTPPutModelSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the http put model source params
func (o *HTTPPutModelSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the http put model source params
func (o *HTTPPutModelSourceParams) WithBody(body *models.RuleSourceBean) *HTTPPutModelSourceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the http put model source params
func (o *HTTPPutModelSourceParams) SetBody(body *models.RuleSourceBean) {
	o.Body = body
}

// WithModelname adds the modelname to the http put model source params
func (o *HTTPPutModelSourceParams) WithModelname(modelname string) *HTTPPutModelSourceParams {
	o.SetModelname(modelname)
	return o
}

// SetModelname adds the modelname to the http put model source params
func (o *HTTPPutModelSourceParams) SetModelname(modelname string) {
	o.Modelname = modelname
}

// WriteToRequest writes these params to a swagger request
func (o *HTTPPutModelSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param modelname
	if err := r.SetPathParam("modelname", o.Modelname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
