// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kihamo/boggart/providers/dom24/models"
)

// DeleteByIdentReader is a Reader for the DeleteByIdent structure.
type DeleteByIdentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteByIdentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteByIdentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteByIdentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteByIdentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteByIdentOK creates a DeleteByIdentOK with default headers values
func NewDeleteByIdentOK() *DeleteByIdentOK {
	return &DeleteByIdentOK{}
}

/*DeleteByIdentOK handles this case with default header values.

Successful operation
*/
type DeleteByIdentOK struct {
}

func (o *DeleteByIdentOK) Error() string {
	return fmt.Sprintf("[POST /User/DeleteAccountByIdent][%d] deleteByIdentOK ", 200)
}

func (o *DeleteByIdentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteByIdentUnauthorized creates a DeleteByIdentUnauthorized with default headers values
func NewDeleteByIdentUnauthorized() *DeleteByIdentUnauthorized {
	return &DeleteByIdentUnauthorized{}
}

/*DeleteByIdentUnauthorized handles this case with default header values.

Unauthorized
*/
type DeleteByIdentUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteByIdentUnauthorized) Error() string {
	return fmt.Sprintf("[POST /User/DeleteAccountByIdent][%d] deleteByIdentUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteByIdentUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteByIdentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteByIdentDefault creates a DeleteByIdentDefault with default headers values
func NewDeleteByIdentDefault(code int) *DeleteByIdentDefault {
	return &DeleteByIdentDefault{
		_statusCode: code,
	}
}

/*DeleteByIdentDefault handles this case with default header values.

Unexpected error
*/
type DeleteByIdentDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete by ident default response
func (o *DeleteByIdentDefault) Code() int {
	return o._statusCode
}

func (o *DeleteByIdentDefault) Error() string {
	return fmt.Sprintf("[POST /User/DeleteAccountByIdent][%d] deleteByIdent default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteByIdentDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteByIdentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteByIdentBody delete by ident body
swagger:model DeleteByIdentBody
*/
type DeleteByIdentBody struct {

	// ident
	Ident string `json:"Ident,omitempty"`
}

// Validate validates this delete by ident body
func (o *DeleteByIdentBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteByIdentBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteByIdentBody) UnmarshalBinary(b []byte) error {
	var res DeleteByIdentBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
