package boggart

const (
	ConfigDevicesManagerCheckInterval   = ComponentName + ".devices-manager.check-interval"
	ConfigDevicesManagerCheckTimeout    = ComponentName + ".devices-manager.check-timeout"
	ConfigListenerTelegramChats         = ComponentName + ".listener.telegram.chats"
	ConfigRS485Address                  = ComponentName + ".rs485.path"
	ConfigRS485Timeout                  = ComponentName + ".rs485.timeout"
	ConfigGPIOEnabled                   = ComponentName + ".gpio.enabled"
	ConfigGPIOPins                      = ComponentName + ".gpio.pins"
	ConfigCameraHikVisionAddresses      = ComponentName + ".camera.hikvision.addresses"
	ConfigCameraHikVisionRepeatInterval = ComponentName + ".camera.hikvision.repeat-interval"
	ConfigMercuryEnabled                = ComponentName + ".mercury.enabled"
	ConfigMercuryRepeatInterval         = ComponentName + ".mercury.repeat-interval"
	ConfigMercuryDeviceAddress          = ComponentName + ".mercury.device-address"

	ConfigMikrotikRepeatInterval = ComponentName + ".mikrotik.repeat-interval"
	ConfigMikrotikAddresses      = ComponentName + ".mikrotik.addresses"
	ConfigMikrotikTimeout        = ComponentName + ".mikrotik.timeout"

	ConfigMobileEnabled               = ComponentName + ".mobile.enabled"
	ConfigMobileRepeatInterval        = ComponentName + ".mobile.repeat-interval"
	ConfigMobileMegafonPhone          = ComponentName + ".mobile.megafon.phone"
	ConfigMobileMegafonPassword       = ComponentName + ".mobile.megafon.password"
	ConfigPulsarEnabled               = ComponentName + ".pulsar.enabled"
	ConfigPulsarRepeatInterval        = ComponentName + ".pulsar.repeat-interval"
	ConfigPulsarHeatMeterAddress      = ComponentName + ".pulsar.heat-meter.address"
	ConfigPulsarColdWaterSerialNumber = ComponentName + ".pulsar.cold-water.serial-number"
	ConfigPulsarColdWaterPulseInput   = ComponentName + ".pulsar.cold-water.pulse-input"
	ConfigPulsarColdWaterStartValue   = ComponentName + ".pulsar.cold-water.start-value"
	ConfigPulsarHotWaterSerialNumber  = ComponentName + ".pulsar.hot-water.serial-number"
	ConfigPulsarHotWaterPulseInput    = ComponentName + ".pulsar.hot-water.pulse-input"
	ConfigPulsarHotWaterStartValue    = ComponentName + ".pulsar.hot-water.start-value"
	ConfigSoftVideoEnabled            = ComponentName + ".softvideo.enabled"
	ConfigSoftVideoRepeatInterval     = ComponentName + ".softvideo.repeat-interval"
	ConfigSoftVideoLogin              = ComponentName + ".softvideo.login"
	ConfigSoftVideoPassword           = ComponentName + ".softvideo.password"
	ConfigSensorBME280Enabled         = ComponentName + ".sensor-bme280.enabled"
	ConfigSensorBME280RepeatInterval  = ComponentName + ".sensor-bme280.repeat-interval"
	ConfigSensorBME280Bus             = ComponentName + ".sensor-bme280.bus"
	ConfigSensorBME280Address         = ComponentName + ".sensor-bme280.address"
	ConfigOwnTracksEnabled            = ComponentName + ".own-tracks.enabled"
)
