package boggart

const (
	ConfigRS485Address              = ComponentName + ".rs485.path"
	ConfigRS485Timeout              = ComponentName + ".rs485.timeout"
	ConfigMercuryEnabled            = ComponentName + ".mercury.enabled"
	ConfigMercuryRepeatInterval     = ComponentName + ".mercury.repeat-interval"
	ConfigMercuryDeviceAddress      = ComponentName + ".mercury.device-address"
	ConfigPulsarEnabled             = ComponentName + ".pulsar.enabled"
	ConfigPulsarRepeatInterval      = ComponentName + ".pulsar.repeat-interval"
	ConfigPulsarHeatMeterAddress    = ComponentName + ".pulsar.heat-meter.address"
	ConfigPulsarColdWaterPulseInput = ComponentName + ".pulsar.cold-water.pulse-input"
	ConfigPulsarColdWaterStartValue = ComponentName + ".pulsar.cold-water.start-value"
	ConfigPulsarHotWaterPulseInput  = ComponentName + ".pulsar.hot-water.pulse-input"
	ConfigPulsarHotWaterStartValue  = ComponentName + ".pulsar.hot-water.start-value"
	ConfigSoftVideoEnabled          = ComponentName + ".softvideo.enabled"
	ConfigSoftVideoRepeatInterval   = ComponentName + ".softvideo.repeat-interval"
	ConfigSoftVideoLogin            = ComponentName + ".softvideo.login"
	ConfigSoftVideoPassword         = ComponentName + ".softvideo.password"
	ConfigMikrotikEnabled           = ComponentName + ".mikrotik.enabled"
	ConfigMikrotikRepeatInterval    = ComponentName + ".mikrotik.repeat-interval"
	ConfigMikrotikAddress           = ComponentName + ".mikrotik.address"
	ConfigMikrotikUsername          = ComponentName + ".mikrotik.username"
	ConfigMikrotikPassword          = ComponentName + ".mikrotik.password"
	ConfigMikrotikTimeout           = ComponentName + ".mikrotik.timeout"
	ConfigDoorsEnabled              = ComponentName + ".doors.enabled"
	ConfigDoorsEntrancePin          = ComponentName + ".doors.entrance-pin"
)
