// Code generated by go-swagger; DO NOT EDIT.

package onecall

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kihamo/boggart/providers/openweathermap/models"
)

// GetOneCallTimeMachineReader is a Reader for the GetOneCallTimeMachine structure.
type GetOneCallTimeMachineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOneCallTimeMachineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOneCallTimeMachineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewGetOneCallTimeMachineTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetOneCallTimeMachineDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetOneCallTimeMachineOK creates a GetOneCallTimeMachineOK with default headers values
func NewGetOneCallTimeMachineOK() *GetOneCallTimeMachineOK {
	return &GetOneCallTimeMachineOK{}
}

/*GetOneCallTimeMachineOK handles this case with default header values.

Successful operation
*/
type GetOneCallTimeMachineOK struct {
	Payload *models.OneCallTimeMachine
}

func (o *GetOneCallTimeMachineOK) Error() string {
	return fmt.Sprintf("[GET /data/2.5/onecall/timemachine?lat={lat}&lon={lon}][%d] getOneCallTimeMachineOK  %+v", 200, o.Payload)
}

func (o *GetOneCallTimeMachineOK) GetPayload() *models.OneCallTimeMachine {
	return o.Payload
}

func (o *GetOneCallTimeMachineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OneCallTimeMachine)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOneCallTimeMachineTooManyRequests creates a GetOneCallTimeMachineTooManyRequests with default headers values
func NewGetOneCallTimeMachineTooManyRequests() *GetOneCallTimeMachineTooManyRequests {
	return &GetOneCallTimeMachineTooManyRequests{}
}

/*GetOneCallTimeMachineTooManyRequests handles this case with default header values.

Account is blocked
*/
type GetOneCallTimeMachineTooManyRequests struct {
	Payload *models.Error
}

func (o *GetOneCallTimeMachineTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /data/2.5/onecall/timemachine?lat={lat}&lon={lon}][%d] getOneCallTimeMachineTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetOneCallTimeMachineTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOneCallTimeMachineTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOneCallTimeMachineDefault creates a GetOneCallTimeMachineDefault with default headers values
func NewGetOneCallTimeMachineDefault(code int) *GetOneCallTimeMachineDefault {
	return &GetOneCallTimeMachineDefault{
		_statusCode: code,
	}
}

/*GetOneCallTimeMachineDefault handles this case with default header values.

Unexpected error
*/
type GetOneCallTimeMachineDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get one call time machine default response
func (o *GetOneCallTimeMachineDefault) Code() int {
	return o._statusCode
}

func (o *GetOneCallTimeMachineDefault) Error() string {
	return fmt.Sprintf("[GET /data/2.5/onecall/timemachine?lat={lat}&lon={lon}][%d] getOneCallTimeMachine default  %+v", o._statusCode, o.Payload)
}

func (o *GetOneCallTimeMachineDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetOneCallTimeMachineDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
