// Code generated by go-swagger; DO NOT EDIT.

package discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDiscoveryServicesParams creates a new GetDiscoveryServicesParams object
// with the default values initialized.
func NewGetDiscoveryServicesParams() *GetDiscoveryServicesParams {

	return &GetDiscoveryServicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDiscoveryServicesParamsWithTimeout creates a new GetDiscoveryServicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDiscoveryServicesParamsWithTimeout(timeout time.Duration) *GetDiscoveryServicesParams {

	return &GetDiscoveryServicesParams{

		timeout: timeout,
	}
}

// NewGetDiscoveryServicesParamsWithContext creates a new GetDiscoveryServicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDiscoveryServicesParamsWithContext(ctx context.Context) *GetDiscoveryServicesParams {

	return &GetDiscoveryServicesParams{

		Context: ctx,
	}
}

// NewGetDiscoveryServicesParamsWithHTTPClient creates a new GetDiscoveryServicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDiscoveryServicesParamsWithHTTPClient(client *http.Client) *GetDiscoveryServicesParams {

	return &GetDiscoveryServicesParams{
		HTTPClient: client,
	}
}

/*
GetDiscoveryServicesParams contains all the parameters to send to the API endpoint
for the get discovery services operation typically these are written to a http.Request
*/
type GetDiscoveryServicesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get discovery services params
func (o *GetDiscoveryServicesParams) WithTimeout(timeout time.Duration) *GetDiscoveryServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get discovery services params
func (o *GetDiscoveryServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get discovery services params
func (o *GetDiscoveryServicesParams) WithContext(ctx context.Context) *GetDiscoveryServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get discovery services params
func (o *GetDiscoveryServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get discovery services params
func (o *GetDiscoveryServicesParams) WithHTTPClient(client *http.Client) *GetDiscoveryServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get discovery services params
func (o *GetDiscoveryServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDiscoveryServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
