// Code generated by go-swagger; DO NOT EDIT.

package streaming

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChannelPictureParams creates a new GetChannelPictureParams object
// with the default values initialized.
func NewGetChannelPictureParams() *GetChannelPictureParams {
	var ()
	return &GetChannelPictureParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChannelPictureParamsWithTimeout creates a new GetChannelPictureParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChannelPictureParamsWithTimeout(timeout time.Duration) *GetChannelPictureParams {
	var ()
	return &GetChannelPictureParams{

		timeout: timeout,
	}
}

// NewGetChannelPictureParamsWithContext creates a new GetChannelPictureParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChannelPictureParamsWithContext(ctx context.Context) *GetChannelPictureParams {
	var ()
	return &GetChannelPictureParams{

		Context: ctx,
	}
}

// NewGetChannelPictureParamsWithHTTPClient creates a new GetChannelPictureParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChannelPictureParamsWithHTTPClient(client *http.Client) *GetChannelPictureParams {
	var ()
	return &GetChannelPictureParams{
		HTTPClient: client,
	}
}

/*GetChannelPictureParams contains all the parameters to send to the API endpoint
for the get channel picture operation typically these are written to a http.Request
*/
type GetChannelPictureParams struct {

	/*Channel
	  Channel ID

	*/
	Channel uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get channel picture params
func (o *GetChannelPictureParams) WithTimeout(timeout time.Duration) *GetChannelPictureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get channel picture params
func (o *GetChannelPictureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get channel picture params
func (o *GetChannelPictureParams) WithContext(ctx context.Context) *GetChannelPictureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get channel picture params
func (o *GetChannelPictureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get channel picture params
func (o *GetChannelPictureParams) WithHTTPClient(client *http.Client) *GetChannelPictureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get channel picture params
func (o *GetChannelPictureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannel adds the channel to the get channel picture params
func (o *GetChannelPictureParams) WithChannel(channel uint64) *GetChannelPictureParams {
	o.SetChannel(channel)
	return o
}

// SetChannel adds the channel to the get channel picture params
func (o *GetChannelPictureParams) SetChannel(channel uint64) {
	o.Channel = channel
}

// WriteToRequest writes these params to a swagger request
func (o *GetChannelPictureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel
	if err := r.SetPathParam("channel", swag.FormatUint64(o.Channel)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
