// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kihamo/boggart/providers/hikvision/models"
)

// GetNtpServersReader is a Reader for the GetNtpServers structure.
type GetNtpServersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNtpServersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNtpServersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /System/time/NtpServers] getNtpServers", response, response.Code())
	}
}

// NewGetNtpServersOK creates a GetNtpServersOK with default headers values
func NewGetNtpServersOK() *GetNtpServersOK {
	return &GetNtpServersOK{}
}

/*
GetNtpServersOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetNtpServersOK struct {
	Payload models.SystemNtpServers
}

// IsSuccess returns true when this get ntp servers o k response has a 2xx status code
func (o *GetNtpServersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get ntp servers o k response has a 3xx status code
func (o *GetNtpServersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ntp servers o k response has a 4xx status code
func (o *GetNtpServersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ntp servers o k response has a 5xx status code
func (o *GetNtpServersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get ntp servers o k response a status code equal to that given
func (o *GetNtpServersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get ntp servers o k response
func (o *GetNtpServersOK) Code() int {
	return 200
}

func (o *GetNtpServersOK) Error() string {
	return fmt.Sprintf("[GET /System/time/NtpServers][%d] getNtpServersOK  %+v", 200, o.Payload)
}

func (o *GetNtpServersOK) String() string {
	return fmt.Sprintf("[GET /System/time/NtpServers][%d] getNtpServersOK  %+v", 200, o.Payload)
}

func (o *GetNtpServersOK) GetPayload() models.SystemNtpServers {
	return o.Payload
}

func (o *GetNtpServersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
