package mqtt

import (
	"github.com/kihamo/snitch"
)

var (
	metricState                 = snitch.NewGauge("state", "Component state")
	metricSensorValue           = snitch.NewGauge("sensor_value", "Export metric esphome_sensor_value")
	metricSensorFailed          = snitch.NewGauge("sensor_failed", "Export metric esphome_sensor_failed")
	metricBinarySensorValue     = snitch.NewGauge("binary_sensor_value", "Export metric esphome_binary_sensor_value")
	metricBinarySensorFailed    = snitch.NewGauge("binary_sensor_failed", "Export metric esphome_binary_sensor_failed")
	metricFanValue              = snitch.NewGauge("fan_value", "Export metric esphome_fan_value")
	metricFanFailed             = snitch.NewGauge("fan_failed", "Export metric esphome_fan_failed")
	metricFanSpeed              = snitch.NewGauge("fan_speed", "Export metric esphome_fan_speed")
	metricFanOscillation        = snitch.NewGauge("fan_oscillation", "Export metric esphome_fan_oscillation")
	metricLightState            = snitch.NewGauge("light_state", "Export metric esphome_light_state")
	metricLightColor            = snitch.NewGauge("light_color", "Export metric esphome_light_color")
	metricLightEffectActive     = snitch.NewGauge("light_effect_active", "Export metric esphome_light_effect_active")
	metricCoverValue            = snitch.NewGauge("cover_value", "Export metric esphome_cover_value")
	metricCoverFailed           = snitch.NewGauge("cover_failed", "Export metric esphome_cover_failed")
	metricSwitchValue           = snitch.NewGauge("cover_value", "Export metric esphome_switch_value")
	metricSwitchFailed          = snitch.NewGauge("cover_failed", "Export metric esphome_switch_failed")
	metricLockValue             = snitch.NewGauge("lock_value", "Export metric esphome_lock_value")
	metricLockFailed            = snitch.NewGauge("lock_failed", "Export metric esphome_lock_failed")
	metricTextSensorValue       = snitch.NewGauge("text_sensor_value", "Export metric esphome_binary_text_value")
	metricTextSensorFailed      = snitch.NewGauge("text_sensor_failed", "Export metric esphome_binary_text_failed")
	metricTextValue             = snitch.NewGauge("text_value", "Export metric esphome_text_value")
	metricTextFailed            = snitch.NewGauge("text_failed", "Export metric esphome_text_failed")
	metricEventValue            = snitch.NewGauge("event_value", "Export metric esphome_event_value")
	metricEventFailed           = snitch.NewGauge("event_failed", "Export metric esphome_event_failed")
	metricNumberValue           = snitch.NewGauge("number_value", "Export metric esphome_number_value")
	metricNumberFailed          = snitch.NewGauge("number_failed", "Export metric esphome_number_failed")
	metricSelectValue           = snitch.NewGauge("select_value", "Export metric esphome_select_value")
	metricSelectFailed          = snitch.NewGauge("select_failed", "Export metric esphome_select_failed")
	metricMediaPlayerStateValue = snitch.NewGauge("media_player_state_value", "Export metric esphome_media_player_state_value")
	metricMediaPlayerVolume     = snitch.NewGauge("media_player_volume", "Export metric esphome_media_player_volume")
	metricMediaPlayerIsMuted    = snitch.NewGauge("media_player_is_muted", "Export metric esphome_media_player_is_muted")
	metricMediaPlayerFailed     = snitch.NewGauge("media_player_failed", "Export metric esphome_media_player_failed")
	metricUpdateEntityState     = snitch.NewGauge("update_entity_state", "Export metric esphome_update_entity_state")
	metricUpdateEntityInfo      = snitch.NewGauge("update_entity_info", "Export metric esphome_update_entity_info")
	metricUpdateEntityFailed    = snitch.NewGauge("update_entity_failed", "Export metric esphome_update_entity_failed")
	metricValveOperation        = snitch.NewGauge("valve_operation", "Export metric esphome_valve_operation")
	metricValveFailed           = snitch.NewGauge("valve_failed", "Export metric esphome_valve_failed")
	metricValvePosition         = snitch.NewGauge("valve_position", "Export metric esphome_valve_position")
	metricClimateSetting        = snitch.NewGauge("climate_setting", "Export metric esphome_climate_setting")
	metricClimateValue          = snitch.NewGauge("climate_value", "Export metric esphome_climate_value")
	metricClimateFailed         = snitch.NewGauge("climate_failed", "Export metric esphome_climate_failed")
)

func (b *Bind) Describe(ch chan<- *snitch.Description) {
	mac := b.Meta().MACAsString()
	if mac == "" {
		return
	}

	metricState.With("mac", mac).Describe(ch)

	if b.IP() != nil {
		metricSensorValue.With("mac", mac).Describe(ch)
		metricSensorFailed.With("mac", mac).Describe(ch)
		metricBinarySensorValue.With("mac", mac).Describe(ch)
		metricBinarySensorFailed.With("mac", mac).Describe(ch)
		metricFanValue.With("mac", mac).Describe(ch)
		metricFanFailed.With("mac", mac).Describe(ch)
		metricFanSpeed.With("mac", mac).Describe(ch)
		metricFanOscillation.With("mac", mac).Describe(ch)
		metricLightState.With("mac", mac).Describe(ch)
		metricLightColor.With("mac", mac).Describe(ch)
		metricLightEffectActive.With("mac", mac).Describe(ch)
		metricCoverValue.With("mac", mac).Describe(ch)
		metricCoverFailed.With("mac", mac).Describe(ch)
		metricSwitchValue.With("mac", mac).Describe(ch)
		metricSwitchFailed.With("mac", mac).Describe(ch)
		metricLockValue.With("mac", mac).Describe(ch)
		metricLockFailed.With("mac", mac).Describe(ch)
		metricTextSensorValue.With("mac", mac).Describe(ch)
		metricTextSensorFailed.With("mac", mac).Describe(ch)
		metricTextValue.With("mac", mac).Describe(ch)
		metricTextFailed.With("mac", mac).Describe(ch)
		metricEventValue.With("mac", mac).Describe(ch)
		metricEventFailed.With("mac", mac).Describe(ch)
		metricNumberValue.With("mac", mac).Describe(ch)
		metricNumberFailed.With("mac", mac).Describe(ch)
		metricSelectValue.With("mac", mac).Describe(ch)
		metricSelectFailed.With("mac", mac).Describe(ch)
		metricMediaPlayerStateValue.With("mac", mac).Describe(ch)
		metricMediaPlayerVolume.With("mac", mac).Describe(ch)
		metricMediaPlayerIsMuted.With("mac", mac).Describe(ch)
		metricMediaPlayerFailed.With("mac", mac).Describe(ch)
		metricUpdateEntityState.With("mac", mac).Describe(ch)
		metricUpdateEntityInfo.With("mac", mac).Describe(ch)
		metricUpdateEntityFailed.With("mac", mac).Describe(ch)
		metricValveOperation.With("mac", mac).Describe(ch)
		metricValveFailed.With("mac", mac).Describe(ch)
		metricValvePosition.With("mac", mac).Describe(ch)
		metricClimateSetting.With("mac", mac).Describe(ch)
		metricClimateValue.With("mac", mac).Describe(ch)
		metricClimateFailed.With("mac", mac).Describe(ch)
	}
}

func (b *Bind) Collect(ch chan<- snitch.Metric) {
	mac := b.Meta().MACAsString()
	if mac == "" {
		return
	}

	metricState.With("mac", mac).Collect(ch)

	if b.IP() != nil {
		metricSensorValue.With("mac", mac).Collect(ch)
		metricSensorFailed.With("mac", mac).Collect(ch)
		metricBinarySensorValue.With("mac", mac).Collect(ch)
		metricBinarySensorFailed.With("mac", mac).Collect(ch)
		metricFanValue.With("mac", mac).Collect(ch)
		metricFanFailed.With("mac", mac).Collect(ch)
		metricFanSpeed.With("mac", mac).Collect(ch)
		metricFanOscillation.With("mac", mac).Collect(ch)
		metricLightState.With("mac", mac).Collect(ch)
		metricLightColor.With("mac", mac).Collect(ch)
		metricLightEffectActive.With("mac", mac).Collect(ch)
		metricCoverValue.With("mac", mac).Collect(ch)
		metricCoverFailed.With("mac", mac).Collect(ch)
		metricSwitchValue.With("mac", mac).Collect(ch)
		metricSwitchFailed.With("mac", mac).Collect(ch)
		metricLockValue.With("mac", mac).Collect(ch)
		metricLockFailed.With("mac", mac).Collect(ch)
		metricTextSensorValue.With("mac", mac).Collect(ch)
		metricTextSensorFailed.With("mac", mac).Collect(ch)
		metricTextValue.With("mac", mac).Collect(ch)
		metricTextFailed.With("mac", mac).Collect(ch)
		metricEventValue.With("mac", mac).Collect(ch)
		metricEventFailed.With("mac", mac).Collect(ch)
		metricNumberValue.With("mac", mac).Collect(ch)
		metricNumberFailed.With("mac", mac).Collect(ch)
		metricSelectValue.With("mac", mac).Collect(ch)
		metricSelectFailed.With("mac", mac).Collect(ch)
		metricMediaPlayerStateValue.With("mac", mac).Collect(ch)
		metricMediaPlayerVolume.With("mac", mac).Collect(ch)
		metricMediaPlayerIsMuted.With("mac", mac).Collect(ch)
		metricMediaPlayerFailed.With("mac", mac).Collect(ch)
		metricUpdateEntityState.With("mac", mac).Collect(ch)
		metricUpdateEntityInfo.With("mac", mac).Collect(ch)
		metricUpdateEntityFailed.With("mac", mac).Collect(ch)
		metricValveOperation.With("mac", mac).Collect(ch)
		metricValveFailed.With("mac", mac).Collect(ch)
		metricValvePosition.With("mac", mac).Collect(ch)
		metricClimateSetting.With("mac", mac).Collect(ch)
		metricClimateValue.With("mac", mac).Collect(ch)
		metricClimateFailed.With("mac", mac).Collect(ch)
	}
}
