// Code generated by go-swagger; DO NOT EDIT.

package things

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetConfigStatusParams creates a new GetConfigStatusParams object
// with the default values initialized.
func NewGetConfigStatusParams() *GetConfigStatusParams {
	var ()
	return &GetConfigStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConfigStatusParamsWithTimeout creates a new GetConfigStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConfigStatusParamsWithTimeout(timeout time.Duration) *GetConfigStatusParams {
	var ()
	return &GetConfigStatusParams{

		timeout: timeout,
	}
}

// NewGetConfigStatusParamsWithContext creates a new GetConfigStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetConfigStatusParamsWithContext(ctx context.Context) *GetConfigStatusParams {
	var ()
	return &GetConfigStatusParams{

		Context: ctx,
	}
}

// NewGetConfigStatusParamsWithHTTPClient creates a new GetConfigStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetConfigStatusParamsWithHTTPClient(client *http.Client) *GetConfigStatusParams {
	var ()
	return &GetConfigStatusParams{
		HTTPClient: client,
	}
}

/*GetConfigStatusParams contains all the parameters to send to the API endpoint
for the get config status operation typically these are written to a http.Request
*/
type GetConfigStatusParams struct {

	/*AcceptLanguage*/
	AcceptLanguage *string
	/*ThingUID
	  thing

	*/
	ThingUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get config status params
func (o *GetConfigStatusParams) WithTimeout(timeout time.Duration) *GetConfigStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get config status params
func (o *GetConfigStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get config status params
func (o *GetConfigStatusParams) WithContext(ctx context.Context) *GetConfigStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get config status params
func (o *GetConfigStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get config status params
func (o *GetConfigStatusParams) WithHTTPClient(client *http.Client) *GetConfigStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get config status params
func (o *GetConfigStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAcceptLanguage adds the acceptLanguage to the get config status params
func (o *GetConfigStatusParams) WithAcceptLanguage(acceptLanguage *string) *GetConfigStatusParams {
	o.SetAcceptLanguage(acceptLanguage)
	return o
}

// SetAcceptLanguage adds the acceptLanguage to the get config status params
func (o *GetConfigStatusParams) SetAcceptLanguage(acceptLanguage *string) {
	o.AcceptLanguage = acceptLanguage
}

// WithThingUID adds the thingUID to the get config status params
func (o *GetConfigStatusParams) WithThingUID(thingUID string) *GetConfigStatusParams {
	o.SetThingUID(thingUID)
	return o
}

// SetThingUID adds the thingUid to the get config status params
func (o *GetConfigStatusParams) SetThingUID(thingUID string) {
	o.ThingUID = thingUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetConfigStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AcceptLanguage != nil {

		// header param Accept-Language
		if err := r.SetHeaderParam("Accept-Language", *o.AcceptLanguage); err != nil {
			return err
		}

	}

	// path param thingUID
	if err := r.SetPathParam("thingUID", o.ThingUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
