// Code generated by go-swagger; DO NOT EDIT.

package things

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetEnabledParams creates a new SetEnabledParams object
// with the default values initialized.
func NewSetEnabledParams() *SetEnabledParams {
	var ()
	return &SetEnabledParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetEnabledParamsWithTimeout creates a new SetEnabledParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetEnabledParamsWithTimeout(timeout time.Duration) *SetEnabledParams {
	var ()
	return &SetEnabledParams{

		timeout: timeout,
	}
}

// NewSetEnabledParamsWithContext creates a new SetEnabledParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetEnabledParamsWithContext(ctx context.Context) *SetEnabledParams {
	var ()
	return &SetEnabledParams{

		Context: ctx,
	}
}

// NewSetEnabledParamsWithHTTPClient creates a new SetEnabledParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetEnabledParamsWithHTTPClient(client *http.Client) *SetEnabledParams {
	var ()
	return &SetEnabledParams{
		HTTPClient: client,
	}
}

/*
SetEnabledParams contains all the parameters to send to the API endpoint
for the set enabled operation typically these are written to a http.Request
*/
type SetEnabledParams struct {

	/*AcceptLanguage*/
	AcceptLanguage *string
	/*Body
	  enabled

	*/
	Body string
	/*ThingUID
	  thing

	*/
	ThingUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set enabled params
func (o *SetEnabledParams) WithTimeout(timeout time.Duration) *SetEnabledParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set enabled params
func (o *SetEnabledParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set enabled params
func (o *SetEnabledParams) WithContext(ctx context.Context) *SetEnabledParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set enabled params
func (o *SetEnabledParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set enabled params
func (o *SetEnabledParams) WithHTTPClient(client *http.Client) *SetEnabledParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set enabled params
func (o *SetEnabledParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAcceptLanguage adds the acceptLanguage to the set enabled params
func (o *SetEnabledParams) WithAcceptLanguage(acceptLanguage *string) *SetEnabledParams {
	o.SetAcceptLanguage(acceptLanguage)
	return o
}

// SetAcceptLanguage adds the acceptLanguage to the set enabled params
func (o *SetEnabledParams) SetAcceptLanguage(acceptLanguage *string) {
	o.AcceptLanguage = acceptLanguage
}

// WithBody adds the body to the set enabled params
func (o *SetEnabledParams) WithBody(body string) *SetEnabledParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set enabled params
func (o *SetEnabledParams) SetBody(body string) {
	o.Body = body
}

// WithThingUID adds the thingUID to the set enabled params
func (o *SetEnabledParams) WithThingUID(thingUID string) *SetEnabledParams {
	o.SetThingUID(thingUID)
	return o
}

// SetThingUID adds the thingUid to the set enabled params
func (o *SetEnabledParams) SetThingUID(thingUID string) {
	o.ThingUID = thingUID
}

// WriteToRequest writes these params to a swagger request
func (o *SetEnabledParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AcceptLanguage != nil {

		// header param Accept-Language
		if err := r.SetHeaderParam("Accept-Language", *o.AcceptLanguage); err != nil {
			return err
		}

	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param thingUID
	if err := r.SetPathParam("thingUID", o.ThingUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
