// Code generated by "enumer -type=CartridgeStatus -trimprefix=CartridgeStatus -output=cartridge_status_enumer.go"; DO NOT EDIT.

package pantum

import (
	"fmt"
	"strings"
)

const _CartridgeStatusName = "UnknownNormalCartridgeNotDetectedCartridgeMismatchCartridgeExpiredCartridgeTonerLow"

var _CartridgeStatusIndex = [...]uint8{0, 7, 13, 33, 50, 66, 83}

const _CartridgeStatusLowerName = "unknownnormalcartridgenotdetectedcartridgemismatchcartridgeexpiredcartridgetonerlow"

func (i CartridgeStatus) String() string {
	i -= -1
	if i < 0 || i >= CartridgeStatus(len(_CartridgeStatusIndex)-1) {
		return fmt.Sprintf("CartridgeStatus(%d)", i+-1)
	}
	return _CartridgeStatusName[_CartridgeStatusIndex[i]:_CartridgeStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CartridgeStatusNoOp() {
	var x [1]struct{}
	_ = x[CartridgeStatusUnknown-(-1)]
	_ = x[CartridgeStatusNormal-(0)]
	_ = x[CartridgeNotDetected-(1)]
	_ = x[CartridgeMismatch-(2)]
	_ = x[CartridgeExpired-(3)]
	_ = x[CartridgeTonerLow-(4)]
}

var _CartridgeStatusValues = []CartridgeStatus{CartridgeStatusUnknown, CartridgeStatusNormal, CartridgeNotDetected, CartridgeMismatch, CartridgeExpired, CartridgeTonerLow}

var _CartridgeStatusNameToValueMap = map[string]CartridgeStatus{
	_CartridgeStatusName[0:7]:        CartridgeStatusUnknown,
	_CartridgeStatusLowerName[0:7]:   CartridgeStatusUnknown,
	_CartridgeStatusName[7:13]:       CartridgeStatusNormal,
	_CartridgeStatusLowerName[7:13]:  CartridgeStatusNormal,
	_CartridgeStatusName[13:33]:      CartridgeNotDetected,
	_CartridgeStatusLowerName[13:33]: CartridgeNotDetected,
	_CartridgeStatusName[33:50]:      CartridgeMismatch,
	_CartridgeStatusLowerName[33:50]: CartridgeMismatch,
	_CartridgeStatusName[50:66]:      CartridgeExpired,
	_CartridgeStatusLowerName[50:66]: CartridgeExpired,
	_CartridgeStatusName[66:83]:      CartridgeTonerLow,
	_CartridgeStatusLowerName[66:83]: CartridgeTonerLow,
}

var _CartridgeStatusNames = []string{
	_CartridgeStatusName[0:7],
	_CartridgeStatusName[7:13],
	_CartridgeStatusName[13:33],
	_CartridgeStatusName[33:50],
	_CartridgeStatusName[50:66],
	_CartridgeStatusName[66:83],
}

// CartridgeStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CartridgeStatusString(s string) (CartridgeStatus, error) {
	if val, ok := _CartridgeStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CartridgeStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CartridgeStatus values", s)
}

// CartridgeStatusValues returns all values of the enum
func CartridgeStatusValues() []CartridgeStatus {
	return _CartridgeStatusValues
}

// CartridgeStatusStrings returns a slice of all String values of the enum
func CartridgeStatusStrings() []string {
	strs := make([]string, len(_CartridgeStatusNames))
	copy(strs, _CartridgeStatusNames)
	return strs
}

// IsACartridgeStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CartridgeStatus) IsACartridgeStatus() bool {
	for _, v := range _CartridgeStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
