// Code generated by "enumer -type=ProductID -trimprefix=ProductID -output=product_id_enumer.go"; DO NOT EDIT.

package pantum

import (
	"fmt"
	"strings"
)

const (
	_ProductIDName_0      = "Unknown"
	_ProductIDLowerName_0 = "unknown"
	_ProductIDName_1      = "P3010DP3010DWP3060DWP3300P3300DNP3300DWM6700DM6700DWM6760DWM6800FDWM6860FDWM7100DNM7100DWM7200FDM7200FDNM7200FDW"
	_ProductIDLowerName_1 = "p3010dp3010dwp3060dwp3300p3300dnp3300dwm6700dm6700dwm6760dwm6800fdwm6860fdwm7100dnm7100dwm7200fdm7200fdnm7200fdw"
	_ProductIDName_2      = "M6700DNM7100D"
	_ProductIDLowerName_2 = "m6700dnm7100d"
	_ProductIDName_3      = "M6860FDN"
	_ProductIDLowerName_3 = "m6860fdn"
	_ProductIDName_4      = "M6760DM7160DW"
	_ProductIDLowerName_4 = "m6760dm7160dw"
	_ProductIDName_5      = "P3012NET"
	_ProductIDLowerName_5 = "p3012net"
	_ProductIDName_6      = "P3100DLP3255DN"
	_ProductIDLowerName_6 = "p3100dlp3255dn"
)

var (
	_ProductIDIndex_0 = [...]uint8{0, 7}
	_ProductIDIndex_1 = [...]uint8{0, 6, 13, 20, 25, 32, 39, 45, 52, 59, 67, 75, 82, 89, 96, 104, 112}
	_ProductIDIndex_2 = [...]uint8{0, 7, 13}
	_ProductIDIndex_3 = [...]uint8{0, 8}
	_ProductIDIndex_4 = [...]uint8{0, 6, 13}
	_ProductIDIndex_5 = [...]uint8{0, 8}
	_ProductIDIndex_6 = [...]uint8{0, 14}
)

func (i ProductID) String() string {
	switch {
	case i == 0:
		return _ProductIDName_0
	case 3780 <= i && i <= 3795:
		i -= 3780
		return _ProductIDName_1[_ProductIDIndex_1[i]:_ProductIDIndex_1[i+1]]
	case 3809 <= i && i <= 3810:
		i -= 3809
		return _ProductIDName_2[_ProductIDIndex_2[i]:_ProductIDIndex_2[i+1]]
	case i == 3831:
		return _ProductIDName_3
	case 3842 <= i && i <= 3843:
		i -= 3842
		return _ProductIDName_4[_ProductIDIndex_4[i]:_ProductIDIndex_4[i+1]]
	case i == 6192:
		return _ProductIDName_5
	case i == 26672:
		return _ProductIDName_6
	default:
		return fmt.Sprintf("ProductID(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProductIDNoOp() {
	var x [1]struct{}
	_ = x[ProductIDUnknown-(0)]
	_ = x[ProductIDP3010D-(3780)]
	_ = x[ProductIDP3010DW-(3781)]
	_ = x[ProductIDP3060DW-(3782)]
	_ = x[ProductIDP3300-(3783)]
	_ = x[ProductIDP3300DN-(3784)]
	_ = x[ProductIDP3300DW-(3785)]
	_ = x[ProductIDM6700D-(3786)]
	_ = x[ProductIDM6700DW-(3787)]
	_ = x[ProductIDM6760DW-(3788)]
	_ = x[ProductIDM6800FDW-(3789)]
	_ = x[ProductIDM6860FDW-(3790)]
	_ = x[ProductIDM7100DN-(3791)]
	_ = x[ProductIDM7100DW-(3792)]
	_ = x[ProductIDM7200FD-(3793)]
	_ = x[ProductIDM7200FDN-(3794)]
	_ = x[ProductIDM7200FDW-(3795)]
	_ = x[ProductIDM6700DN-(3809)]
	_ = x[ProductIDM7100D-(3810)]
	_ = x[ProductIDM6860FDN-(3831)]
	_ = x[ProductIDM6760D-(3842)]
	_ = x[ProductIDM7160DW-(3843)]
	_ = x[ProductIDP3012NET-(6192)]
	_ = x[ProductIDP3100DLP3255DN-(26672)]
}

var _ProductIDValues = []ProductID{ProductIDUnknown, ProductIDP3010D, ProductIDP3010DW, ProductIDP3060DW, ProductIDP3300, ProductIDP3300DN, ProductIDP3300DW, ProductIDM6700D, ProductIDM6700DW, ProductIDM6760DW, ProductIDM6800FDW, ProductIDM6860FDW, ProductIDM7100DN, ProductIDM7100DW, ProductIDM7200FD, ProductIDM7200FDN, ProductIDM7200FDW, ProductIDM6700DN, ProductIDM7100D, ProductIDM6860FDN, ProductIDM6760D, ProductIDM7160DW, ProductIDP3012NET, ProductIDP3100DLP3255DN}

var _ProductIDNameToValueMap = map[string]ProductID{
	_ProductIDName_0[0:7]:          ProductIDUnknown,
	_ProductIDLowerName_0[0:7]:     ProductIDUnknown,
	_ProductIDName_1[0:6]:          ProductIDP3010D,
	_ProductIDLowerName_1[0:6]:     ProductIDP3010D,
	_ProductIDName_1[6:13]:         ProductIDP3010DW,
	_ProductIDLowerName_1[6:13]:    ProductIDP3010DW,
	_ProductIDName_1[13:20]:        ProductIDP3060DW,
	_ProductIDLowerName_1[13:20]:   ProductIDP3060DW,
	_ProductIDName_1[20:25]:        ProductIDP3300,
	_ProductIDLowerName_1[20:25]:   ProductIDP3300,
	_ProductIDName_1[25:32]:        ProductIDP3300DN,
	_ProductIDLowerName_1[25:32]:   ProductIDP3300DN,
	_ProductIDName_1[32:39]:        ProductIDP3300DW,
	_ProductIDLowerName_1[32:39]:   ProductIDP3300DW,
	_ProductIDName_1[39:45]:        ProductIDM6700D,
	_ProductIDLowerName_1[39:45]:   ProductIDM6700D,
	_ProductIDName_1[45:52]:        ProductIDM6700DW,
	_ProductIDLowerName_1[45:52]:   ProductIDM6700DW,
	_ProductIDName_1[52:59]:        ProductIDM6760DW,
	_ProductIDLowerName_1[52:59]:   ProductIDM6760DW,
	_ProductIDName_1[59:67]:        ProductIDM6800FDW,
	_ProductIDLowerName_1[59:67]:   ProductIDM6800FDW,
	_ProductIDName_1[67:75]:        ProductIDM6860FDW,
	_ProductIDLowerName_1[67:75]:   ProductIDM6860FDW,
	_ProductIDName_1[75:82]:        ProductIDM7100DN,
	_ProductIDLowerName_1[75:82]:   ProductIDM7100DN,
	_ProductIDName_1[82:89]:        ProductIDM7100DW,
	_ProductIDLowerName_1[82:89]:   ProductIDM7100DW,
	_ProductIDName_1[89:96]:        ProductIDM7200FD,
	_ProductIDLowerName_1[89:96]:   ProductIDM7200FD,
	_ProductIDName_1[96:104]:       ProductIDM7200FDN,
	_ProductIDLowerName_1[96:104]:  ProductIDM7200FDN,
	_ProductIDName_1[104:112]:      ProductIDM7200FDW,
	_ProductIDLowerName_1[104:112]: ProductIDM7200FDW,
	_ProductIDName_2[0:7]:          ProductIDM6700DN,
	_ProductIDLowerName_2[0:7]:     ProductIDM6700DN,
	_ProductIDName_2[7:13]:         ProductIDM7100D,
	_ProductIDLowerName_2[7:13]:    ProductIDM7100D,
	_ProductIDName_3[0:8]:          ProductIDM6860FDN,
	_ProductIDLowerName_3[0:8]:     ProductIDM6860FDN,
	_ProductIDName_4[0:6]:          ProductIDM6760D,
	_ProductIDLowerName_4[0:6]:     ProductIDM6760D,
	_ProductIDName_4[6:13]:         ProductIDM7160DW,
	_ProductIDLowerName_4[6:13]:    ProductIDM7160DW,
	_ProductIDName_5[0:8]:          ProductIDP3012NET,
	_ProductIDLowerName_5[0:8]:     ProductIDP3012NET,
	_ProductIDName_6[0:14]:         ProductIDP3100DLP3255DN,
	_ProductIDLowerName_6[0:14]:    ProductIDP3100DLP3255DN,
}

var _ProductIDNames = []string{
	_ProductIDName_0[0:7],
	_ProductIDName_1[0:6],
	_ProductIDName_1[6:13],
	_ProductIDName_1[13:20],
	_ProductIDName_1[20:25],
	_ProductIDName_1[25:32],
	_ProductIDName_1[32:39],
	_ProductIDName_1[39:45],
	_ProductIDName_1[45:52],
	_ProductIDName_1[52:59],
	_ProductIDName_1[59:67],
	_ProductIDName_1[67:75],
	_ProductIDName_1[75:82],
	_ProductIDName_1[82:89],
	_ProductIDName_1[89:96],
	_ProductIDName_1[96:104],
	_ProductIDName_1[104:112],
	_ProductIDName_2[0:7],
	_ProductIDName_2[7:13],
	_ProductIDName_3[0:8],
	_ProductIDName_4[0:6],
	_ProductIDName_4[6:13],
	_ProductIDName_5[0:8],
	_ProductIDName_6[0:14],
}

// ProductIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProductIDString(s string) (ProductID, error) {
	if val, ok := _ProductIDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProductIDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProductID values", s)
}

// ProductIDValues returns all values of the enum
func ProductIDValues() []ProductID {
	return _ProductIDValues
}

// ProductIDStrings returns a slice of all String values of the enum
func ProductIDStrings() []string {
	strs := make([]string, len(_ProductIDNames))
	copy(strs, _ProductIDNames)
	return strs
}

// IsAProductID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProductID) IsAProductID() bool {
	for _, v := range _ProductIDValues {
		if i == v {
			return true
		}
	}
	return false
}
