// Code generated by go-swagger; DO NOT EDIT.

package habmin_floorplan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewHTTPDeleteFloorplanParams creates a new HTTPDeleteFloorplanParams object
// with the default values initialized.
func NewHTTPDeleteFloorplanParams() *HTTPDeleteFloorplanParams {
	var ()
	return &HTTPDeleteFloorplanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHTTPDeleteFloorplanParamsWithTimeout creates a new HTTPDeleteFloorplanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHTTPDeleteFloorplanParamsWithTimeout(timeout time.Duration) *HTTPDeleteFloorplanParams {
	var ()
	return &HTTPDeleteFloorplanParams{

		timeout: timeout,
	}
}

// NewHTTPDeleteFloorplanParamsWithContext creates a new HTTPDeleteFloorplanParams object
// with the default values initialized, and the ability to set a context for a request
func NewHTTPDeleteFloorplanParamsWithContext(ctx context.Context) *HTTPDeleteFloorplanParams {
	var ()
	return &HTTPDeleteFloorplanParams{

		Context: ctx,
	}
}

// NewHTTPDeleteFloorplanParamsWithHTTPClient creates a new HTTPDeleteFloorplanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHTTPDeleteFloorplanParamsWithHTTPClient(client *http.Client) *HTTPDeleteFloorplanParams {
	var ()
	return &HTTPDeleteFloorplanParams{
		HTTPClient: client,
	}
}

/*HTTPDeleteFloorplanParams contains all the parameters to send to the API endpoint
for the http delete floorplan operation typically these are written to a http.Request
*/
type HTTPDeleteFloorplanParams struct {

	/*FloorplanID*/
	FloorplanID int32
	/*Type*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) WithTimeout(timeout time.Duration) *HTTPDeleteFloorplanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) WithContext(ctx context.Context) *HTTPDeleteFloorplanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) WithHTTPClient(client *http.Client) *HTTPDeleteFloorplanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFloorplanID adds the floorplanID to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) WithFloorplanID(floorplanID int32) *HTTPDeleteFloorplanParams {
	o.SetFloorplanID(floorplanID)
	return o
}

// SetFloorplanID adds the floorplanId to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) SetFloorplanID(floorplanID int32) {
	o.FloorplanID = floorplanID
}

// WithType adds the typeVar to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) WithType(typeVar *string) *HTTPDeleteFloorplanParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the http delete floorplan params
func (o *HTTPDeleteFloorplanParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *HTTPDeleteFloorplanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param floorplanID
	if err := r.SetPathParam("floorplanID", swag.FormatInt32(o.FloorplanID)); err != nil {
		return err
	}

	if o.Type != nil {

		// query param type
		var qrType string
		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {
			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
