// Code generated by go-swagger; DO NOT EDIT.

package habmin_floorplan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// HTTPDeleteFloorplanReader is a Reader for the HTTPDeleteFloorplan structure.
type HTTPDeleteFloorplanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HTTPDeleteFloorplanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewHTTPDeleteFloorplanDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewHTTPDeleteFloorplanDefault creates a HTTPDeleteFloorplanDefault with default headers values
func NewHTTPDeleteFloorplanDefault(code int) *HTTPDeleteFloorplanDefault {
	return &HTTPDeleteFloorplanDefault{
		_statusCode: code,
	}
}

/*HTTPDeleteFloorplanDefault handles this case with default header values.

successful operation
*/
type HTTPDeleteFloorplanDefault struct {
	_statusCode int
}

// Code gets the status code for the http delete floorplan default response
func (o *HTTPDeleteFloorplanDefault) Code() int {
	return o._statusCode
}

func (o *HTTPDeleteFloorplanDefault) Error() string {
	return fmt.Sprintf("[DELETE /habmin/floorplan/{floorplanID}][%d] httpDeleteFloorplan default ", o._statusCode)
}

func (o *HTTPDeleteFloorplanDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
