// Code generated by go-swagger; DO NOT EDIT.

package habmin_floorplan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// HTTPGetFloorplanReader is a Reader for the HTTPGetFloorplan structure.
type HTTPGetFloorplanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HTTPGetFloorplanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	result := NewHTTPGetFloorplanDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result

}

// NewHTTPGetFloorplanDefault creates a HTTPGetFloorplanDefault with default headers values
func NewHTTPGetFloorplanDefault(code int) *HTTPGetFloorplanDefault {
	return &HTTPGetFloorplanDefault{
		_statusCode: code,
	}
}

/*HTTPGetFloorplanDefault handles this case with default header values.

successful operation
*/
type HTTPGetFloorplanDefault struct {
	_statusCode int
}

// Code gets the status code for the http get floorplan default response
func (o *HTTPGetFloorplanDefault) Code() int {
	return o._statusCode
}

func (o *HTTPGetFloorplanDefault) Error() string {
	return fmt.Sprintf("[GET /habmin/floorplan/{floorplanID}][%d] httpGetFloorplan default ", o._statusCode)
}

func (o *HTTPGetFloorplanDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
