---
swagger: "2.0"
info:
  title: "Keenetic"
  version: "3.9.5"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "http"
basePath: "/"
paths:
  /auth:
    get:
      operationId: "getAuth"
      tags:
        - "user"
      responses:
        200:
          description: "Successful operation"
        401:
          $ref: "#/responses/Unauthorized"
    post:
      operationId: "postAuth"
      tags:
        - "user"
      parameters:
        - name: "request"
          in: "body"
          schema:
            type: "object"
            properties:
              login:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "Successful operation"
  /rci/show/defaults:
    get:
      operationId: "showDefaults"
      tags:
        - "show"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ShowDefaultsResponse"
        401:
          $ref: "#/responses/Unauthorized"
  /rci/show/system:
    get:
      operationId: "showSystem"
      tags:
        - "show"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ShowSystemResponse"
        401:
          $ref: "#/responses/Unauthorized"
  /rci/show/version:
    get:
      operationId: "showVersion"
      tags:
        - "show"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ShowVersionResponse"
        401:
          $ref: "#/responses/Unauthorized"

responses:
  Unauthorized:
    description: "Unauthorized operation"
    headers:
      WWW-Authenticate:
        type: "string"
      X-NDM-Challenge:
        type: "string"
      X-NDM-Realm:
        type: "string"

definitions:
  IntegerAsString:
    type: "integer"
    x-go-type:
      import:
        alias: "extend"
        package: "github.com/kihamo/boggart/protocols/swagger"
      type: "IntegerAsString"
    x-nullable: false

  ContinuedResponse:
    type: "object"
    properties:
      continued:
        type: "boolean"

  ShowDefaultsResponse:
    type: "object"
    properties:
      servicetag:
        type: "string"
      servicehost:
        type: "string"
      servicepass:
        type: "string"
      wlanssid:
        type: "string"
      wlankey:
        type: "string"
      wlanwps:
        type: "string"
      country:
        type: "string"
      ndmhwid:
        type: "string"
      product:
        type: "string"
      ctrlsum:
        type: "string"
      serial:
        type: "string"
      signature:
        type: "string"
      integrity:
        type: "string"
      locked:
        type: "boolean"

  ShowSystemResponse:
    type: "object"
    properties:
      hostname:
        type: "string"
      domainname:
        type: "string"
      cpuload:
        type: "integer"
      memory:
        type: "string"
      swap:
        type: "string"
      memtotal:
        type: "integer"
      memfree:
        type: "integer"
      membuffers:
        type: "integer"
      memcache:
        type: "integer"
      swaptotal:
        type: "integer"
      swapfree:
        type: "integer"
      uptime:
        $ref: "#/definitions/IntegerAsString"

  ShowVersionResponse:
    type: "object"
    properties:
      release:
        type: "string"
      sandbox:
        type: "string"
      title:
        type: "string"
      arch:
        type: "string"
