---
swagger: "2.0"
info:
  title: "Keenetic"
  version: "3.9.5"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "http"
basePath: "/"
paths:
  /auth:
    get:
      operationId: "getAuth"
      tags:
        - "user"
      responses:
        200:
          description: "Successful operation"
        401:
          $ref: "#/responses/Unauthorized"
    post:
      operationId: "postAuth"
      tags:
        - "user"
      parameters:
        - name: "request"
          in: "body"
          schema:
            type: "object"
            properties:
              login:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "Successful operation"
  /rci/show/defaults:
    get:
      operationId: "showDefaults"
      tags:
        - "show"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ShowDefaultsResponse"
        401:
          $ref: "#/responses/Unauthorized"
  /rci/show/ip/hotspot:
    get:
      operationId: "showIPHotspot"
      tags:
        - "show"
      parameters:
        - name: "mac"
          in: "query"
          description: "Filter by mac"
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ShowIPHotspotResponse"
        401:
          $ref: "#/responses/Unauthorized"
  /rci/show/system:
    get:
      operationId: "showSystem"
      tags:
        - "show"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ShowSystemResponse"
        401:
          $ref: "#/responses/Unauthorized"
  /rci/show/version:
    get:
      operationId: "showVersion"
      tags:
        - "show"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/ShowVersionResponse"
        401:
          $ref: "#/responses/Unauthorized"

responses:
  Unauthorized:
    description: "Unauthorized operation"
    headers:
      WWW-Authenticate:
        type: "string"
      X-NDM-Challenge:
        type: "string"
      X-NDM-Realm:
        type: "string"

definitions:
  IntegerAsString:
    type: "integer"
    x-go-type:
      import:
        alias: "extend"
        package: "github.com/kihamo/boggart/protocols/swagger"
      type: "IntegerAsString"
    x-nullable: false

  ContinuedResponse:
    type: "object"
    properties:
      continued:
        type: "boolean"

  ShowDefaultsResponse:
    type: "object"
    properties:
      servicetag:
        type: "string"
      servicehost:
        type: "string"
      servicepass:
        type: "string"
      wlanssid:
        type: "string"
      wlankey:
        type: "string"
      wlanwps:
        type: "string"
      country:
        type: "string"
      ndmhwid:
        type: "string"
      product:
        type: "string"
      ctrlsum:
        type: "string"
      serial:
        type: "string"
      signature:
        type: "string"
      integrity:
        type: "string"
      locked:
        type: "boolean"

  ShowIPHotspotResponse:
    type: "object"
    properties:
      host:
        type: "array"
        items:
          type: "object"
          properties:
            mac:
              type: "string"
            via:
              type: "string"
            ip:
              type: "string"
            hostname:
              type: "string"
            name:
              type: "string"
            interface:
              type: "object"
              properties:
                id:
                  type: "string"
                name:
                  type: "string"
                description:
                  type: "string"
            dhcp:
              type: "object"
              properties:
                static:
                  type: "boolean"
            registered:
              type: "boolean"
            access:
              type: "string"
            schedule:
              type: "string"
            priority:
              type: "integer"
            active:
              type: "boolean"
            rxbytes:
              type: "integer"
            txbytes:
              type: "integer"
            first-seen:
              type: "integer"
            last-seen:
              type: "integer"
            link:
              type: "string"
            mws:
              type: "object"
              description: "Mesh Wi-Fi System"
              properties:
                cid:
                  type: "string"
                ap:
                  type: "string"
                authenticated:
                  type: "boolean"
                txrate:
                  type: "integer"
                  description: "TX rate in Mbit/sec"
                uptime:
                  type: "integer"
                ht:
                  type: "integer"
                  description: "ширина канала"
                mode:
                  type: "string"
                gi:
                  type: "integer"
                  description: "защитный интервал"
                rssi:
                  type: "integer"
                  description: "уровень сигнала; показатель уровня мощности принимаемого сигнала; чем выше это число, или чем оно менее отрицательное, тем мощнее сигнал"
                mcs:
                  type: "integer"
                  description: "индекс модуляции и схемы кодирования"
                txss:
                  type: "integer"
                  description: "пространственный поток"
                ebf:
                  type: "boolean"
                dl-mu:
                  type: "boolean"
                _11:
                  type: "array"
                  items:
                    type: "string"
                security:
                  type: "string"
            traffic-shape:
              type: "object"
              properties:
                rx:
                  type: "integer"
                tx:
                  type: "integer"
                mode:
                  type: "string"
                schedule:
                  type: "string"

            # ethernet
            auto-negotiation:
              type: "boolean"
            speed:
              type: "integer"
            duplex:
              type: "boolean"
            port:
              type: "string"

            # wifi
            ssid:
              type: "string"
            ap:
              type: "string"
            authenticated:
              type: "boolean"
            txrate:
              type: "integer"
            uptime:
              type: "integer"
            ht:
              type: "integer"
            mode:
              type: "string"
            gi:
              type: "integer"
            rssi:
              type: "integer"
            mcs:
              type: "integer"
            txss:
              type: "integer"
            ebf:
              type: "boolean"
            dl-mu:
              type: "boolean"
            _11:
              type: "array"
              items:
                type: "string"
            security:
              type: "string"

  ShowSystemResponse:
    type: "object"
    properties:
      hostname:
        type: "string"
      domainname:
        type: "string"
      cpuload:
        type: "integer"
      memory:
        type: "string"
      swap:
        type: "string"
      memtotal:
        type: "integer"
      memfree:
        type: "integer"
      membuffers:
        type: "integer"
      memcache:
        type: "integer"
      swaptotal:
        type: "integer"
      swapfree:
        type: "integer"
      uptime:
        $ref: "#/definitions/IntegerAsString"

  ShowVersionResponse:
    type: "object"
    properties:
      release:
        type: "string"
      sandbox:
        type: "string"
      title:
        type: "string"
      arch:
        type: "string"
