---
swagger: "2.0"
info:
  title: "Wiim"
  version: "1.2"
consumes:
- "text/html"
produces:
- "text/html"
schemes:
- "https"
basePath: "/"
paths:
  /httpapi.asp?command=getStatusEx:
    get:
      operationId: "getStatusEx"
      description: "Retrieves detailed informations about a connected device."
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/StatusEx"

  /httpapi.asp?command=wlanGetConnectState:
    get:
      operationId: "wlanGetConnectState"
      description: "This command will return the status of the WiFi connection. The possible return values are as follows."
      responses:
        200:
          description: >
            PROCESS	- Connection still in progress.
            PAIRFAIL- WiFi connection attempt failed. Wrong password given.
            FAIL- WiFi connection attempt failed. Also this will be the reply for a device that is connected by LAN Ethernet port.
            OK - Device is connected.
          schema:
            type: "string"
            enum:
              - "PROCESS"  # Connection still in progress.
              - "PAIRFAIL" # Wrong password
              - "FAIL"     # Connect fail
              - "OK"       # connected
 
  /httpapi.asp?command=EQGetList:
    get:
      operationId: "EQGetList"
      description: "Check all the possible EQ settings"
      responses:
        200:
          description: "Successful"
          schema:
            type: "array"
            items: 
              type: "string"

definitions:
  BooleanAsString:
    type: "string"
    x-go-type:
      import:
        alias: "extend"
        package: "github.com/kihamo/boggart/protocols/swagger"
      type: "BooleanAsString"
    x-nullable: false

  IntegerAsString:
    type: "string"
    x-go-type:
      import:
        alias: "extend"
        package: "github.com/kihamo/boggart/protocols/swagger"
      type: "IntegerAsString"
    x-nullable: false

  HEXString:
    type: "string"
    x-go-type:
      import:
        alias: "extend"
        package: "github.com/kihamo/boggart/protocols/swagger"
      type: "HEXString"
    x-nullable: false

  MAC:
    type: "string"
    x-go-type:
      import:
        alias: "extend"
        package: "github.com/kihamo/boggart/protocols/swagger"
      type: "MAC"
    x-nullable: false


  StatusEx:
    type: "object"
    properties:
      language:
        type: "string"
      ssid:
        type: "string"
        description: "Name of the device"
      hideSSID:
        $ref: "#/definitions/BooleanAsString"
        description: "SSID of the WiFi the device is connected to [hexed string]"
      firmware:
        type: "string"
        description: "Current firmware version"
      build:
        type: "string"
        enum:
          - "release"
          - "debug"
          - "backup"
      project:
        type: "string"
        description: "The project name"
      priv_prj:
        type: "string"
        description: "Project name which would stand for a specific board"
      project_build_name: # not in docs
        type: "string"
        description: "Code identifier for customized release"
      Release:
        type: "string"
        description: "Firmware build date in format: YYYYMMDD"
      FW_Release_version:
        type: "string"
        description: "Reserved"
      PCB_version: # not in docs
        type: "string" 
      cast_enable: # not in docs
        $ref: "#/definitions/BooleanAsString"
      cast_usage_report: # not in docs
        $ref: "#/definitions/BooleanAsString"
      group:
        $ref: "#/definitions/IntegerAsString"
        description: "0 means it's a master speaker, 1 means a slave speaker in a group"
      wmrm_version:
        type: "string"
        description: "LinkPlay's MRM SDK version, version 4.2 or above won't work with any version below 4.2"
      expired:
        $ref: "#/definitions/BooleanAsString"
        description: "Reserved"
      internet:
        $ref: "#/definitions/BooleanAsString"
        description: >
          Current status of internet access:
          0: not ready
          1: ready
      uuid:
        type: "string"
        description: "The unique ID of the device"
      MAC:
        $ref: "#/definitions/MAC"
        description: "MAC address of the device when working in hotspot mode, will show on APP and also the sticker on module/device."
      BTMAC: # BT_MAC in docs, BTMAC real device
        $ref: "#/definitions/MAC"
        description: "The BT MAC address of the device"
      InitialConfiguration: # not in docs
        $ref: "#/definitions/BooleanAsString"
      temperature_power_control: # not in docs
        $ref: "#/definitions/IntegerAsString"
      temperature_cpu: # not in docs
        $ref: "#/definitions/IntegerAsString"
      temperature_tmp102: # not in docs
        $ref: "#/definitions/IntegerAsString"
      AP_MAC:
        $ref: "#/definitions/MAC"
        description: "The MAC address of the AP that the device is connected to"
      date: 
        type: "string"
        description: "Current Date"
      time: 
        type: "string"
        description: "Current local time"
      netstat: # not in docs
        $ref: "#/definitions/IntegerAsString"
        description: >
          WiFi connect state:
          0: no connection
          1: connecting
          2: connected
      essid: 
        $ref: "#/definitions/HEXString"
        description: "The AP name in the HEX format"
      apcli0:
        type: "string"
        description: " The IP v4 address of the device"
      eth0:
        type: "string"
      eth2: # not in docs
        type: "string"
      ETH_MAC:
        $ref: "#/definitions/MAC"
      hardware:
        type: "string"
        description: "Hardware model"
      ota_api_ver: # not in docs
        type: "string"
      VersionUpdate:
        $ref: "#/definitions/BooleanAsString"
        description: >
          0: No new version
          1: new version.
      NewVer:
        type: "string"
        description: "If there is a new firmware available (in case of VersionUpdate is set to 1), this is the new version number"
      mcu_ver:
        type: "string"
        description: "Version of MCU on base board"
      mcu_ver_new:
        type: "string"
        description: >
          New version of MCU on base board, indicates if there is a newer version of MCU available. 
          0 - No new version
          others - New version"
      hdmi_ver: # not in docs
        type: "string"
      hdmi_ver_new: # not in docs
        type: "string"
      update_check_count:
        $ref: "#/definitions/IntegerAsString"
      BleRemote_update_checked_counter: # not in docs
        $ref: "#/definitions/IntegerAsString"
      ra0:
        type: "string"
      temp_uuid:
        type: "string"
        description: "Temporary UUID (will change after device reboot)"
      cap1:
        $ref: "#/definitions/IntegerAsString"
        description: "Bit mask for the module feature, used internally"
      capability:
        $ref: "#/definitions/IntegerAsString"
        description: "Bit mask for the module feature, used internally"
      languages:
        type: "string"
      prompt_status:
        $ref: "#/definitions/BooleanAsString"
        description: >
          Indicates if the prompting voice would be played or not, you can set with command PromptEnable and PromptDisable. 
          0 - No prompting voice
          1 - Have prompting voice
      alexa_ver:
        type: "string"
      alexa_beta_enable:
        $ref: "#/definitions/BooleanAsString"
      alexa_force_beta_cfg:
        $ref: "#/definitions/BooleanAsString"
      dsp_ver:
        type: "string"
        description: "Version for voice processing, not used"
      ModuleColorNumber: # not in docs
        $ref: "#/definitions/IntegerAsString"
      ModuleColorString: # not in docs
        type: "string"
      dsp_ver_new:
        type: "string"
        description: "New version for voice processing, not used"
      uboot_verinfo: # not in docs
        type: "string"
      silence_ota_flag: # not in docs
        $ref: "#/definitions/BooleanAsString"
      ota_interface_ver:
        type: "string"
      streams_all:
        type: "string"
      streams:
        $ref: "#/definitions/IntegerAsString"
        description: >
          0: If Airplay is enabled
          1: If DLNA is enabled
          2: Has TTPod support
          3: Has TuneIn support
          4: Has Pandora support
          5: Has DoubanFM support
      region:
        type: "string"
      volume_control:
        $ref: "#/definitions/IntegerAsString"
      external:
        type: "string"
        description: "hexadecimal value"
      preset_key:
        $ref: "#/definitions/IntegerAsString"
        description: "Number of preset keys"
      plm_support:
        $ref: "#/definitions/IntegerAsString"
        description: >
          This is a bit mask, each bit stands for an external input source:
          bit1: LineIn (Aux support)
          bit2: Bluetooth support
          bit3: USB support
          bit4: Optical support
          bit6: Coaxial support
          bit8: LineIn 2 support
          bit15: USBDAC support
          Others are reserved or not used.
      mqtt_support: # not in docs
        $ref: "#/definitions/BooleanAsString"
      lbc_support:
        $ref: "#/definitions/BooleanAsString"
      WifiChannel:
        $ref: "#/definitions/IntegerAsString"
        description: "The current connected WiFi channel"
      RSSI:
        $ref: "#/definitions/IntegerAsString"
        description: >
          RSSI Level of used WiFi
          Value ranges from 0 - 100. 100 means best signal strength.
      BSSID:
        type: "string"
        description: "The Basic Service Set Identifiers : In most cases this will be the MAC Address of the Wireless Acces Point Used (e.g. Router)"
      wlanSnr: # not in docs
        $ref: "#/definitions/IntegerAsString"
      wlanNoise: # not in docs
        $ref: "#/definitions/IntegerAsString"
      wlanFreq:
        $ref: "#/definitions/IntegerAsString"
      wlanDataRate:
        $ref: "#/definitions/IntegerAsString"
      battery:
        $ref: "#/definitions/BooleanAsString"
        description: >
          0: battery is not charging
          1: battery is charging
      battery_percent:
        $ref: "#/definitions/IntegerAsString"
        description: >
          Battery charge level
          Value ranges from 0 - 100
      securemode:
        $ref: "#/definitions/IntegerAsString"
      upnp_version:
        type: "string"
        description: "UPnP Device Architecture Version"
      upnp_uuid:
        type: "string"
        description: "The UPnP UUID"
      uart_pass_port:
        $ref: "#/definitions/IntegerAsString"
        description: "Port used for TCP/IP Communcations/Socket Connections"
      communication_port:
        $ref: "#/definitions/IntegerAsString"
        description: "TCP port for internal messages"
      web_firmware_update_hide:
        $ref: "#/definitions/BooleanAsString"
      new_tunein_preset_and_alarm: # not in docs
        $ref: "#/definitions/BooleanAsString"
      new_iheart_podcast: # not in docs
        $ref: "#/definitions/BooleanAsString"
      tidal_version:
        type: "string"
      service_version:
        type: "string"
      HiFiSRC_version:
        type: "string"
      EQ_support:
        type: "string"
      EQVersion: # not in docs
        type: "string"
      audio_channel_config: # not in docs
        type: "string"
      app_timezone_id: # not in docs
        type: "string"
      avs_timezone_id: # not in docs
        type: "string"
      tz_info_ver: # not in docs
        type: "string"
      tz: # not in docs
        type: "string"
        description: "Offset of timezone"
      max_volume: # not in docs
        $ref: "#/definitions/IntegerAsString"
      power_mode:
        $ref: "#/definitions/IntegerAsString"
      security:
        type: "string"
      security_version:
        type: "string"
      security_capabilities:
        type: "object"
        properties: 
          ver:
            type: "string"
          aes_ver:
            type: "string"
      public_https_version:
        type: "string"
      BleRemoteControl: # not in docs
        $ref: "#/definitions/BooleanAsString"
      BleRemoteConnected: # not in docs
        $ref: "#/definitions/BooleanAsString"
      udisk: # not in docs
        $ref: "#/definitions/IntegerAsString"
      umount: # not in docs
        $ref: "#/definitions/IntegerAsString"
      autoSenseVersion: # not in docs
        type: "string"
      set_play_mode_enable: # not in docs
        $ref: "#/definitions/BooleanAsString"
      set_play_mode_gain: # not in docs
        $ref: "#/definitions/BooleanAsString"
      audioOutputModeVer: # not in docs
        type: "string"
      privacy_mode:
        $ref: "#/definitions/BooleanAsString"
      DeviceName:
        type: "string"
        description: "The device UPnP and Airplay friendly name"
      GroupName:
        type: "string"