// Code generated by go-swagger; DO NOT EDIT.

package presets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPresetInfoParams creates a new GetPresetInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPresetInfoParams() *GetPresetInfoParams {
	return &GetPresetInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPresetInfoParamsWithTimeout creates a new GetPresetInfoParams object
// with the ability to set a timeout on a request.
func NewGetPresetInfoParamsWithTimeout(timeout time.Duration) *GetPresetInfoParams {
	return &GetPresetInfoParams{
		timeout: timeout,
	}
}

// NewGetPresetInfoParamsWithContext creates a new GetPresetInfoParams object
// with the ability to set a context for a request.
func NewGetPresetInfoParamsWithContext(ctx context.Context) *GetPresetInfoParams {
	return &GetPresetInfoParams{
		Context: ctx,
	}
}

// NewGetPresetInfoParamsWithHTTPClient creates a new GetPresetInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPresetInfoParamsWithHTTPClient(client *http.Client) *GetPresetInfoParams {
	return &GetPresetInfoParams{
		HTTPClient: client,
	}
}

/*
GetPresetInfoParams contains all the parameters to send to the API endpoint

	for the get preset info operation.

	Typically these are written to a http.Request.
*/
type GetPresetInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get preset info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPresetInfoParams) WithDefaults() *GetPresetInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get preset info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPresetInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get preset info params
func (o *GetPresetInfoParams) WithTimeout(timeout time.Duration) *GetPresetInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get preset info params
func (o *GetPresetInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get preset info params
func (o *GetPresetInfoParams) WithContext(ctx context.Context) *GetPresetInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get preset info params
func (o *GetPresetInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get preset info params
func (o *GetPresetInfoParams) WithHTTPClient(client *http.Client) *GetPresetInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get preset info params
func (o *GetPresetInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPresetInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
