// Code generated by go-swagger; DO NOT EDIT.

package voice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDefaultVoiceParams creates a new GetDefaultVoiceParams object
// with the default values initialized.
func NewGetDefaultVoiceParams() *GetDefaultVoiceParams {

	return &GetDefaultVoiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDefaultVoiceParamsWithTimeout creates a new GetDefaultVoiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDefaultVoiceParamsWithTimeout(timeout time.Duration) *GetDefaultVoiceParams {

	return &GetDefaultVoiceParams{

		timeout: timeout,
	}
}

// NewGetDefaultVoiceParamsWithContext creates a new GetDefaultVoiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDefaultVoiceParamsWithContext(ctx context.Context) *GetDefaultVoiceParams {

	return &GetDefaultVoiceParams{

		Context: ctx,
	}
}

// NewGetDefaultVoiceParamsWithHTTPClient creates a new GetDefaultVoiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDefaultVoiceParamsWithHTTPClient(client *http.Client) *GetDefaultVoiceParams {

	return &GetDefaultVoiceParams{
		HTTPClient: client,
	}
}

/*GetDefaultVoiceParams contains all the parameters to send to the API endpoint
for the get default voice operation typically these are written to a http.Request
*/
type GetDefaultVoiceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get default voice params
func (o *GetDefaultVoiceParams) WithTimeout(timeout time.Duration) *GetDefaultVoiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get default voice params
func (o *GetDefaultVoiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get default voice params
func (o *GetDefaultVoiceParams) WithContext(ctx context.Context) *GetDefaultVoiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get default voice params
func (o *GetDefaultVoiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get default voice params
func (o *GetDefaultVoiceParams) WithHTTPClient(client *http.Client) *GetDefaultVoiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get default voice params
func (o *GetDefaultVoiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDefaultVoiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
