// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOfferParams creates a new GetOfferParams object
// with the default values initialized.
func NewGetOfferParams() *GetOfferParams {

	return &GetOfferParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOfferParamsWithTimeout creates a new GetOfferParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOfferParamsWithTimeout(timeout time.Duration) *GetOfferParams {

	return &GetOfferParams{

		timeout: timeout,
	}
}

// NewGetOfferParamsWithContext creates a new GetOfferParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOfferParamsWithContext(ctx context.Context) *GetOfferParams {

	return &GetOfferParams{

		Context: ctx,
	}
}

// NewGetOfferParamsWithHTTPClient creates a new GetOfferParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOfferParamsWithHTTPClient(client *http.Client) *GetOfferParams {

	return &GetOfferParams{
		HTTPClient: client,
	}
}

/*GetOfferParams contains all the parameters to send to the API endpoint
for the get offer operation typically these are written to a http.Request
*/
type GetOfferParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get offer params
func (o *GetOfferParams) WithTimeout(timeout time.Duration) *GetOfferParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get offer params
func (o *GetOfferParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get offer params
func (o *GetOfferParams) WithContext(ctx context.Context) *GetOfferParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get offer params
func (o *GetOfferParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get offer params
func (o *GetOfferParams) WithHTTPClient(client *http.Client) *GetOfferParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get offer params
func (o *GetOfferParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetOfferParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
