// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Stats stats
// swagger:model Stats
type Stats struct {

	// historically succeeded
	HistoricallySucceeded bool `json:"historically_succeeded,omitempty"`

	// num check connectivity
	NumCheckConnectivity int64 `json:"num_check_connectivity,omitempty"`

	// num connect wifi
	NumConnectWifi int64 `json:"num_connect_wifi,omitempty"`

	// num connected wifi not saved
	NumConnectedWifiNotSaved int64 `json:"num_connected_wifi_not_saved,omitempty"`

	// num initial eureka info
	NumInitialEurekaInfo int64 `json:"num_initial_eureka_info,omitempty"`

	// num obtain ip
	NumObtainIP int64 `json:"num_obtain_ip,omitempty"`
}

// Validate validates this stats
func (m *Stats) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Stats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Stats) UnmarshalBinary(b []byte) error {
	var res Stats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
