// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ChannelTypeUID channel type UID
// swagger:model ChannelTypeUID
type ChannelTypeUID struct {

	// as string
	AsString string `json:"asString,omitempty"`

	// binding Id
	BindingID string `json:"bindingId,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this channel type UID
func (m *ChannelTypeUID) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChannelTypeUID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChannelTypeUID) UnmarshalBinary(b []byte) error {
	var res ChannelTypeUID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
