// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DesignerCommentBean designer comment bean
// swagger:model DesignerCommentBean
type DesignerCommentBean struct {

	// h
	H int32 `json:"h,omitempty"`

	// pinned
	Pinned *bool `json:"pinned,omitempty"`

	// text
	Text string `json:"text,omitempty"`

	// w
	W int32 `json:"w,omitempty"`
}

// Validate validates this designer comment bean
func (m *DesignerCommentBean) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DesignerCommentBean) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DesignerCommentBean) UnmarshalBinary(b []byte) error {
	var res DesignerCommentBean
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
