// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// FloorplanHotspotConfigBean floorplan hotspot config bean
// swagger:model FloorplanHotspotConfigBean
type FloorplanHotspotConfigBean struct {

	// item Id
	ItemID string `json:"itemId,omitempty"`

	// pos x
	PosX float64 `json:"posX,omitempty"`

	// pos y
	PosY float64 `json:"posY,omitempty"`
}

// Validate validates this floorplan hotspot config bean
func (m *FloorplanHotspotConfigBean) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FloorplanHotspotConfigBean) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FloorplanHotspotConfigBean) UnmarshalBinary(b []byte) error {
	var res FloorplanHotspotConfigBean
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
