package mqtt

const (
	ConfigClientID                = ComponentName + ".client-id"
	ConfigUsername                = ComponentName + ".username"
	ConfigPassword                = ComponentName + ".password"
	ConfigClearSession            = ComponentName + ".clear-session"
	ConfigResumeSubs              = ComponentName + ".resume-subs"
	ConfigOrderMatters            = ComponentName + ".order-matters"
	ConfigServers                 = ComponentName + ".servers"
	ConfigConnectionTimeout       = ComponentName + ".connection.timeout"
	ConfigConnectionRetryEnabled  = ComponentName + ".connection.retry-enabled"
	ConfigConnectionRetryInterval = ComponentName + ".connection.retry-interval"
	ConfigKeepAlive               = ComponentName + ".keep-alive"
	ConfigWriteTimeout            = ComponentName + ".write-timeout"
	ConfigPingTimeout             = ComponentName + ".ping-timeout"
	ConfigTokenWaitTimeout        = ComponentName + ".token-wait-timeout"
	ConfigReconnectEnabled        = ComponentName + ".reconnect.enabled"
	ConfigReconnectMaxInterval    = ComponentName + ".reconnect.max-interval"
	ConfigLWTEnabled              = ComponentName + ".lwt.enabled"
	ConfigLWTTopic                = ComponentName + ".lwt.topic"
	ConfigLWTPayload              = ComponentName + ".lwt.payload"
	ConfigLWTQOS                  = ComponentName + ".lwt.qos"
	ConfigLWTRetained             = ComponentName + ".lwt.retained"
	ConfigPayloadCacheEnabled     = ComponentName + ".cache.payload.enabled"
	ConfigPayloadCacheSize        = ComponentName + ".cache.payload.size"
)
