// Code generated by go-swagger; DO NOT EDIT.

package accounting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAccountingInfoParams creates a new AccountingInfoParams object
// with the default values initialized.
func NewAccountingInfoParams() *AccountingInfoParams {

	return &AccountingInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAccountingInfoParamsWithTimeout creates a new AccountingInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAccountingInfoParamsWithTimeout(timeout time.Duration) *AccountingInfoParams {

	return &AccountingInfoParams{

		timeout: timeout,
	}
}

// NewAccountingInfoParamsWithContext creates a new AccountingInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewAccountingInfoParamsWithContext(ctx context.Context) *AccountingInfoParams {

	return &AccountingInfoParams{

		Context: ctx,
	}
}

// NewAccountingInfoParamsWithHTTPClient creates a new AccountingInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAccountingInfoParamsWithHTTPClient(client *http.Client) *AccountingInfoParams {

	return &AccountingInfoParams{
		HTTPClient: client,
	}
}

/*AccountingInfoParams contains all the parameters to send to the API endpoint
for the accounting info operation typically these are written to a http.Request
*/
type AccountingInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the accounting info params
func (o *AccountingInfoParams) WithTimeout(timeout time.Duration) *AccountingInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accounting info params
func (o *AccountingInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accounting info params
func (o *AccountingInfoParams) WithContext(ctx context.Context) *AccountingInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accounting info params
func (o *AccountingInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accounting info params
func (o *AccountingInfoParams) WithHTTPClient(client *http.Client) *AccountingInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accounting info params
func (o *AccountingInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AccountingInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
