// Code generated by go-swagger; DO NOT EDIT.

package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/kihamo/boggart/providers/octoprint/models"
)

// GetSDStateReader is a Reader for the GetSDState structure.
type GetSDStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSDStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSDStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetSDStateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSDStateOK creates a GetSDStateOK with default headers values
func NewGetSDStateOK() *GetSDStateOK {
	return &GetSDStateOK{}
}

/*GetSDStateOK handles this case with default header values.

Successful operation
*/
type GetSDStateOK struct {
	Payload *models.SDState
}

func (o *GetSDStateOK) Error() string {
	return fmt.Sprintf("[GET /api/printer/sd][%d] getSDStateOK  %+v", 200, o.Payload)
}

func (o *GetSDStateOK) GetPayload() *models.SDState {
	return o.Payload
}

func (o *GetSDStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SDState)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSDStateNotFound creates a GetSDStateNotFound with default headers values
func NewGetSDStateNotFound() *GetSDStateNotFound {
	return &GetSDStateNotFound{}
}

/*GetSDStateNotFound handles this case with default header values.

I SD support has been disabled in OctoPrint's config
*/
type GetSDStateNotFound struct {
}

func (o *GetSDStateNotFound) Error() string {
	return fmt.Sprintf("[GET /api/printer/sd][%d] getSDStateNotFound ", 404)
}

func (o *GetSDStateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
