// Code generated by go-swagger; DO NOT EDIT.

package printer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBedStateParams creates a new GetBedStateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBedStateParams() *GetBedStateParams {
	return &GetBedStateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBedStateParamsWithTimeout creates a new GetBedStateParams object
// with the ability to set a timeout on a request.
func NewGetBedStateParamsWithTimeout(timeout time.Duration) *GetBedStateParams {
	return &GetBedStateParams{
		timeout: timeout,
	}
}

// NewGetBedStateParamsWithContext creates a new GetBedStateParams object
// with the ability to set a context for a request.
func NewGetBedStateParamsWithContext(ctx context.Context) *GetBedStateParams {
	return &GetBedStateParams{
		Context: ctx,
	}
}

// NewGetBedStateParamsWithHTTPClient creates a new GetBedStateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBedStateParamsWithHTTPClient(client *http.Client) *GetBedStateParams {
	return &GetBedStateParams{
		HTTPClient: client,
	}
}

/*
GetBedStateParams contains all the parameters to send to the API endpoint

	for the get bed state operation.

	Typically these are written to a http.Request.
*/
type GetBedStateParams struct {

	/* History.

	   The printer’s temperature history by supplying
	*/
	History *bool

	/* Limit.

	   The amount of data points limited
	*/
	Limit *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get bed state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBedStateParams) WithDefaults() *GetBedStateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get bed state params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBedStateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get bed state params
func (o *GetBedStateParams) WithTimeout(timeout time.Duration) *GetBedStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bed state params
func (o *GetBedStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bed state params
func (o *GetBedStateParams) WithContext(ctx context.Context) *GetBedStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bed state params
func (o *GetBedStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bed state params
func (o *GetBedStateParams) WithHTTPClient(client *http.Client) *GetBedStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bed state params
func (o *GetBedStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHistory adds the history to the get bed state params
func (o *GetBedStateParams) WithHistory(history *bool) *GetBedStateParams {
	o.SetHistory(history)
	return o
}

// SetHistory adds the history to the get bed state params
func (o *GetBedStateParams) SetHistory(history *bool) {
	o.History = history
}

// WithLimit adds the limit to the get bed state params
func (o *GetBedStateParams) WithLimit(limit *int64) *GetBedStateParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get bed state params
func (o *GetBedStateParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WriteToRequest writes these params to a swagger request
func (o *GetBedStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.History != nil {

		// query param history
		var qrHistory bool

		if o.History != nil {
			qrHistory = *o.History
		}
		qHistory := swag.FormatBool(qrHistory)
		if qHistory != "" {

			if err := r.SetQueryParam("history", qHistory); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
