// Code generated by go-swagger; DO NOT EDIT.

package inbox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewApproveParams creates a new ApproveParams object
// with the default values initialized.
func NewApproveParams() *ApproveParams {
	var ()
	return &ApproveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewApproveParamsWithTimeout creates a new ApproveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewApproveParamsWithTimeout(timeout time.Duration) *ApproveParams {
	var ()
	return &ApproveParams{

		timeout: timeout,
	}
}

// NewApproveParamsWithContext creates a new ApproveParams object
// with the default values initialized, and the ability to set a context for a request
func NewApproveParamsWithContext(ctx context.Context) *ApproveParams {
	var ()
	return &ApproveParams{

		Context: ctx,
	}
}

// NewApproveParamsWithHTTPClient creates a new ApproveParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewApproveParamsWithHTTPClient(client *http.Client) *ApproveParams {
	var ()
	return &ApproveParams{
		HTTPClient: client,
	}
}

/*
ApproveParams contains all the parameters to send to the API endpoint
for the approve operation typically these are written to a http.Request
*/
type ApproveParams struct {

	/*AcceptLanguage
	  language

	*/
	AcceptLanguage *string
	/*Body
	  thing label

	*/
	Body string
	/*ThingUID
	  thingUID

	*/
	ThingUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the approve params
func (o *ApproveParams) WithTimeout(timeout time.Duration) *ApproveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the approve params
func (o *ApproveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the approve params
func (o *ApproveParams) WithContext(ctx context.Context) *ApproveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the approve params
func (o *ApproveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the approve params
func (o *ApproveParams) WithHTTPClient(client *http.Client) *ApproveParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the approve params
func (o *ApproveParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAcceptLanguage adds the acceptLanguage to the approve params
func (o *ApproveParams) WithAcceptLanguage(acceptLanguage *string) *ApproveParams {
	o.SetAcceptLanguage(acceptLanguage)
	return o
}

// SetAcceptLanguage adds the acceptLanguage to the approve params
func (o *ApproveParams) SetAcceptLanguage(acceptLanguage *string) {
	o.AcceptLanguage = acceptLanguage
}

// WithBody adds the body to the approve params
func (o *ApproveParams) WithBody(body string) *ApproveParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the approve params
func (o *ApproveParams) SetBody(body string) {
	o.Body = body
}

// WithThingUID adds the thingUID to the approve params
func (o *ApproveParams) WithThingUID(thingUID string) *ApproveParams {
	o.SetThingUID(thingUID)
	return o
}

// SetThingUID adds the thingUid to the approve params
func (o *ApproveParams) SetThingUID(thingUID string) {
	o.ThingUID = thingUID
}

// WriteToRequest writes these params to a swagger request
func (o *ApproveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AcceptLanguage != nil {

		// header param Accept-Language
		if err := r.SetHeaderParam("Accept-Language", *o.AcceptLanguage); err != nil {
			return err
		}

	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param thingUID
	if err := r.SetPathParam("thingUID", o.ThingUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
