// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SetStateEngineeringRequest set state engineering request
//
// swagger:model SetStateEngineeringRequest
type SetStateEngineeringRequest struct {

	// id
	ID int64 `json:"id,omitempty"`

	// target
	// Enum: [eng]
	Target string `json:"target,omitempty"`

	// value
	Value int64 `json:"value,omitempty"`
}

// Validate validates this set state engineering request
func (m *SetStateEngineeringRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTarget(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var setStateEngineeringRequestTypeTargetPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["eng"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		setStateEngineeringRequestTypeTargetPropEnum = append(setStateEngineeringRequestTypeTargetPropEnum, v)
	}
}

const (

	// SetStateEngineeringRequestTargetEng captures enum value "eng"
	SetStateEngineeringRequestTargetEng string = "eng"
)

// prop value enum
func (m *SetStateEngineeringRequest) validateTargetEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, setStateEngineeringRequestTypeTargetPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SetStateEngineeringRequest) validateTarget(formats strfmt.Registry) error {
	if swag.IsZero(m.Target) { // not required
		return nil
	}

	// value enum
	if err := m.validateTargetEnum("target", "body", m.Target); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this set state engineering request based on context it is used
func (m *SetStateEngineeringRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SetStateEngineeringRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SetStateEngineeringRequest) UnmarshalBinary(b []byte) error {
	var res SetStateEngineeringRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
